#
# https://activemq.apache.org/apollo/index.html
#
# http://soundcloud.com/daveseaman/radio-therapy-march-2013/download
#
# http://www.jmkg.co.uk/2010/08/31/installing-activemq-on-ubuntu/
#
# log at: /var/lib/activemq/main/data/activemq.log
#
# http://rburnham.wordpress.com/2012/09/14/installing-and-managing-activemq-on-centos/
#
---
- hosts: all

  vars_files:
    - activemq_vars.yml

  tasks:
### REDHAT
  - name: Download {{tgz}}
    get_url: url={{url}}/{{tgz}}
             dest=/root/{{tgz}}
    when: ansible_os_family == "RedHat"
    tags:
      - packages

  - name: Uncompress {{tgz}}
    shell: /bin/tar -C /opt -xzf /root/{{tgz}}
    when: ansible_os_family == "RedHat"
    tags:
      - packages

  - name: Link /opt/activemq
    file: src=/opt/{{pkg}}
          dest=/opt/activemq
          state=link
    when: ansible_os_family == "RedHat"
    tags:
      - packages

  - name: Create activemq user
    user: name=activemq
          home=/var/lib/activemq
    when: ansible_os_family == "RedHat"
    tags:
      - packages

  - name: Install activemq config
    template: src=etc/default/activemq.j2
              dest=/etc/default/activemq
              owner=root
              group=root
              mode=0600
    when: ansible_os_family == "RedHat"
    tags:
      - services

  - name: Install service
    template: src=etc/init.d/activemq.j2
              dest=/etc/init.d/activemq
              owner=root
              group=root
              mode=0755
    when: ansible_os_family == "RedHat"
    tags:
      - services

  - name: Install config
    template: src=opt/activemq/conf/activemq.xml.j2
              dest=/opt/activemq/conf/activemq.xml
              backup=yes
    when: ansible_os_family == "RedHat"
    notify:
      - Restart activemq
    tags:
      - config

### DEBIAN
  - name: Install packages
    apt: name=$item
         state=installed
    with_items:
      - activemq
      - python-stompy
      - libactivemq-java
      - libactivemq-protobuf-java
      - libactivemq-activeio-java
    when: ansible_os_family == "Debian"
    tags:
      - packages

  - name: Install main instance directory
    file: path=/etc/activemq/instances-enabled/main
          state=directory
    when: ansible_os_family == "Debian"
    tags:
      - directories
      - config

  - name: Install main config
    template: src=etc/activemq/instances-available/main/activemq.xml.j2
              dest=/etc/activemq/instances-enabled/main/activemq.xml
              backup=yes
    when: ansible_os_family == "Debian"
    notify:
      - Restart activemq
    tags:
      - config

  - name: Install main log
    template: src=etc/activemq/instances-available/main/log4j.properties.j2
              dest=/etc/activemq/instances-enabled/main/log4j.properties
              backup=yes
    when: ansible_os_family == "Debian"
    tags:
      - config
    notify:
      - Restart activemq


### SERVICES
  - name: Start ActiveMQ
    service: name=activemq
             state=started
             enabled=yes

  handlers:
    - name: Restart activemq
      service: name=activemq
               state=restarted
