#
# http://ajenti.org/
#
---
- hosts: all

  tasks:
### REDHAT
    - name: Install Ajenti Repo
      template: src=etc/yum.repos.d/ajenti.repo.j2
                dest=/etc/yum.repos.d/ajenti.repo
                owner=root
                group=root
                mode=0644
      when: ansible_os_family == "RedHat"
      tags:
        - repo

    - name: Install Ajenti packages
      yum: name=$item
           state=installed
      with_items:
        - ajenti
      when: ansible_os_family == "RedHat"
      tags:
        - packages

### DEBIAN
    - name: Install Ajenti Repo
      apt_repository: repo='deb http://repo.ajenti.org/debian main main'
      when: ansible_os_family == "Debian"
      tags:
        - packages
        - repo

    - name: Install Ajenti Key
      apt_key: url=http://repo.ajenti.org/debian/key
               state=present
      when: ansible_os_family == "Debian"
      tags:
        - packages
        - repo
        - key

    - name: Install Ajenti packages
      apt: name=$item
           state=installed
           force=yes
      with_items:
        - ajenti
      when: ansible_os_family == "Debian"
      tags:
        - packages

### CONFIGURATION
    - name: Install /etc/shorewall/rules.d/ajenti
      template: src=etc/shorewall/rules.d/ajenti_home.j2
                dest=/etc/shorewall/rules.d/ajenti
                owner=root
                group=root
                mode=0640
      tags:
        - firewall
      notify:
        - Restart shorewall

  handlers:
    - name: Restart shorewall
      service: name=shorewall
               state=restarted
