---
- hosts: all
  tasks:

  - name: Install ruby packages
    yum: name=$item
    with_items:
      - make
      - gcc
      - gcc-c++
      - zlib-devel
      - libxml2-devel
      - libxslt-devel
    when: ansible_os_family == "RedHat"
    tags:
      - packages

  - name: Copy RVM Installer
    copy: src=root/install_rvm.sh
          dest=/root/install_rvm.sh
          owner=root
          group=root
          mode=0700
    tags:
      - packages

  - name: Install RVM
    shell: /root/install_rvm.sh
    tags:
      - packages

  - name: Install RVM prompt
    template: src=etc/profile.d/rvm-ps1.sh.j2
              dest=/etc/profile.d/90-rvm-ps1.sh
              owner=root
              group=root
              mode=0644
    tags:
      - config

  - name: Fix global ruby path
    file: src=/usr/local/rvm/rubies/ruby-2.0.0-p0/bin/$item
          dest=/usr/bin/$item
          state=link
    with_items:
      - ruby
      - gem
    tags:
      - fix

