# Switch to permissive mode
# TODO: enforced
---
- hosts: all

  tasks:
    - name: Install selinux packages
#      yum: name=$item state=installed
#      with_items:
#        - libsemanage
#        - setools-libs-python
#        - policycoreutils-python
#        - libselinux-python

      yum: name=libsemanage
           state=installed
      yum: name=setools-libs-python
           state=installed
      yum: name=policycoreutils-python
           state=installed
      yum: name=libselinux-python
           state=installed

    - name: Set selinux permissive policy
      lineinfile: dest=/etc/sysconfig/selinux
                regexp='^SELINUX='
                line='SELINUX=permissive'
      tags:
        - policy
