---
- hosts: all

  vars_files:
    - ruby_vars.yml

  tasks:
### PACKAGES
  - name: Install ruby packages
    yum: name=$item
    with_items:
      - make
      - gcc
      - gcc-c++
      - zlib-devel
      - libxml2-devel
      - libxslt-devel
    when: ansible_os_family == "RedHat"
    tags:
      - packages

### DEBIAN
  - name: Install ruby packages
    apt: name=$item
    with_items:
      - make
      - gcc
      - g++
      - zlib1g-dev
      - libxml2-dev
      - libxslt1-dev
    when: ansible_os_family == "Debian"
    tags:
      - packages

  # https://github.com/Softmotions/ejdb/wiki/Debian-Ubuntu-installation
  - name: Install ejdb repo
    apt_repository: repo='deb http://ppa.launchpad.net/adamansky/ejdb/ubuntu quantal main'
    when: ansible_os_family == "Debian"
    tags:
      - repo
      - ejdb

  # https://launchpad.net/~adamansky/+archive/ejdb
  - name: Install ejdb packages
    apt: name=$item
    with_items:
      - libtcejdb9
      - libtcejdb9-dev
      - libtcejdb9-dbg
    when: ansible_os_family == "Debian"
    tags:
      - packages
      - ejdb

  - name: Install ejdb ruby binding
    git: repo='git://github.com/Softmotions/ejdb.git'
         dest=/opt/ejdb
    tags:
      - ejdb
      - packages

  - name: Compile ejdb
    shell: 'cd /opt/ejdb;make;'
    tags:
      - ejdb

  - name: Compile rbejdb ruby
    shell: 'cd /opt/ejdb/rbejdb;make&&make install;'
    tags:
      - ejdb

### RVM
  - name: Copy RVM Installer
    template: src=root/install_rvm.j2
              dest=/root/install_rvm
              owner=root
              group=root
              mode=0700
    tags:
      - packages

  - name: Install RVM
    shell: /root/install_rvm
    tags:
      - packages
      - rvm

  - name: Install RVM prompt
    template: src=etc/profile.d/rvm-ps1.sh.j2
              dest=/etc/profile.d/90-rvm-ps1.sh
              owner=root
              group=root
              mode=0644
    tags:
      - config
      - rvm

  - name: Fix global ruby path
    file: src=/usr/local/rvm/rubies/{{ruby.version}}/bin/$item
          dest=/usr/bin/$item
          state=link
    with_items:
      - ruby
      - gem
    tags:
      - fix
      - rvm
