# Switch to permissive mode
# TODO: enforced
---
- hosts: all

  tasks:
    - name: Install prerequisite packages
      yum: name=$item
           state=installed
      with_items:
        - libsemanage
        - setools-libs-python
        - policycoreutils-python
        - libselinux-python
        - policycoreutils-python
      tags:
        - packages

  - name: Set permissive policy
    lineinfile: dest=/etc/sysconfig/selinux
                regexp='^SELINUX='
                line='SELINUX=permissive'
    tags:
      - policy
