---
- hosts: all

  tasks:
  - name: Install libsemanage
    yum: name=libsemanage
         state=installed

  - name: Install setools-libs-python
    yum: name=setools-libs-python
         state=installed

  - name: Install policycoreutils-python
    yum: name=policycoreutils-python
         state=installed

  - name: Install libselinux-python
    yum: name=libselinux-python
         state=installed

  - name: Install semanage
    yum: name=policycoreutils-python
         state=installed

  - name: Permissive policy
    lineinfile: dest=/etc/sysconfig/selinux
                regexp='^SELINUX='
                line='SELINUX=permissive'

#  - name: Permissive policy
#    selinux: policy=targeted
#             state=permissive
