# Setup basic services
# rsyslog is replaced by syslog-ng
---
- name: Basic server install
  hosts: all

- include: dnsmasq.yml
- include: ntp_server.yml
- include: syslog-ng.yml
- include: syslog-ng_loghost.yml
