---
- name: Setup basic services
  hosts: all

- include: dnsmasq.yml
- include: ntp_server.yml
- include: syslog-ng.yml
- include: syslog-ng_loghost.yml
- include: syslog-ng_client.yml
- include: logcheck.yml
