#
# Only for RedHat based systems
#
# Switch to permissive mode
# TODO: enforced
---
- hosts: all

  tasks:
    - name: Install selinux packages
      yum: name=$item state=installed
      with_items:
        - libsemanage
        - setools-libs-python
        - policycoreutils-python
        - libselinux-python
      when: ansible_os_family == "RedHat"
      tags:
        - packages

#
# https://www.centos.org/docs/5/html/5.2/Deployment_Guide/sec-sel-enable-disable.html
#
# Shorewall update has an selinux prolem: /etc/init.d/shorewall
#

    - name: Set selinux permissive policy
      lineinfile: dest=/etc/selinux/config
                regexp='^SELINUX='
                line='SELINUX=permissive'
                backup=yes
      when: ansible_os_family == "RedHat"
      tags:
        - policy
