#
# Basic httpd settings
#
---
- hosts: all

  vars_files:
    - networks.yml

  tasks:

  - name: Enable HTTP server status
    template: src=etc/httpd/conf.d/status.conf.j2
              dest=/etc/httpd/conf.d/status.conf
              owner=root
              group=root
              mode=0644
    notify:
      - Restart httpd

  - name: Set HTTP server name
    template: src=etc/httpd/conf.d/servername.conf.j2
              dest=/etc/httpd/conf.d/servername.conf
              owner=root
              group=root
              mode=0644
    notify:
      - Restart httpd

  - name: Allow HTTP connect
    seboolean: name=httpd_can_network_connect
               state=true
               persistent=yes
    notify:
      - Restart httpd

#  - name: Put HTTP in permissive mode
#    command: /usr/sbin/semanage permissive -a httpd_t

  - name: Start httpd
    service: name=httpd
             state=started

  handlers:
    - name: Restart httpd
      service: name=httpd
               state=restarted
