# This play enables dnsmasq DNS cache. Put /etc/hosts 
# entries into /etc/dnsmasq.d/
#
# Not detect root servers:
#
#     --extra-vars "nodetect=yes"
#
# Use dnsmasq for /etc/hosts
#     --extra-vars "usehosts=no"
#
---
- hosts: all

  vars:
    nodetect: "no"
    usehosts: "yes"

  vars_files:
    - networks.yml

  tasks:
#    - name: Install dnsmasq packages
#      yum: name=$item state=installed
#      with_items:
#        - dnsmasq
#        - dnsmasq-utils
#        - bind-utils
#      tags:
#        - packages

    - name: Install dnsmasq
      yum: name=dnsmasq
           state=installed
      tags:
        - packages

    - name: Install dnsmasq-utils
      yum: name=dnsmasq-utils
           state=installed
      tags:
        - packages

    - name: Install bind-utils
      yum: name=bind-utils
           state=installed
      tags:
        - packages

    - name: Enable /etc/dnsmasq.d
      lineinfile: dest=/etc/dnsmasq.conf
                  regexp='^conf-dir.*'
                  insertafter='^#conf-dir.*'
                  line='conf-dir=/etc/dnsmasq.d'
      notify:
        - Restart dnsmasq
      tags:
        - configs

    - name: Create hosts.d directory
      file: path=/etc/hosts.d
            owner=root
            group=root
            state=directory
      tags:
        - hosts

    - name: Enable /etc/hosts.d
      lineinfile: dest=/etc/dnsmasq.conf
                  regexp='^addn-hosts.*'
                  insertafter='^#addn-hosts.*'
                  line='addn-hosts=/etc/hosts.d'
      notify:
        - Restart dnsmasq
      tags:
        - hosts

    - name: Enable root server hostnames
      template: src=etc/hosts.d/root.j2
                dest=/etc/hosts.d/root
                owner=bin
                group=wheel
                mode=0644
      when_string: "'$usehosts' == 'no'"
      notify:
        - Restart dnsmasq
      tags:
        - hosts

    - name: Disable root server hostnames
      file: path=/etc/hosts.d/root
            state=absent
      when_string: "'$usehosts' == 'yes'"
      notify:
        - Restart dnsmasq
      tags:
        - hosts

    - name: Install /etc/hosts
      template: src=etc/hosts.j2
                dest=/etc/hosts
                owner=bin
                group=wheel
                mode=0644
      when_string: "'$usehosts' == 'yes'"
      notify:
        - Restart dnsmasq
      tags:
        - hosts

    - name: Enable networks in /etc/networks
      template: src=etc/networks.j2
                dest=/etc/networks
                owner=bin
                group=wheel
                mode=0644
      tags:
        - networks

    - name: Localhost DNS in /etc/resolv.conf
      lineinfile: dest=/etc/resolv.conf
                  regexp='^nameserver 127.0.0.1'
                  insertbefore='^nameserver.*'
                  line='nameserver 127.0.0.1'
      tags:
        - resolv

    - name: Localhost DNS for DHCP (${interfaces.dhcp})
      template: src=etc/dhcp/dhclient-${interfaces.dhcp}.conf.j2
                dest=/etc/dhcp/dhclient-${interfaces.dhcp}.conf
                owner=root
                group=root
      when_string: "'${interfaces.dhcp}' != ''"
      tags:
        - dhcp

    - name: Start dnsmasq
      service: name=dnsmasq
               state=started
               enabled=yes

  handlers:
    - name: Restart dnsmasq
      service: name=dnsmasq
               state=restarted
