# This play enables dnsmasq DNS cache. Put /etc/hosts 
# entries into /etc/dnsmasq.d/
---
- hosts: all

  vars_files:
    - networks.yml

  tasks:
    - name: Install packages
      yum: name=$item
           state=installed
      with_items:
        - dnsmasq
        - dnsmasq-utils
        - bind-utils
      tags:
        - packages

    - name: Enable /etc/dnsmasq.d
      lineinfile: dest=/etc/dnsmasq.conf
                  regexp='^conf-dir.*'
                  insertafter='^#conf-dir.*'
                  line='conf-dir=/etc/dnsmasq.d'
      notify:
        - restart dnsmasq

    - name: Create hosts.d directory
      file: path=/etc/hosts.d
            owner=root
            group=root
            state=directory

    - name: Enable /etc/hosts.d
      lineinfile: dest=/etc/dnsmasq.conf
                  regexp='^addn-hosts.*'
                  insertafter='^#addn-hosts.*'
                  line='addn-hosts=/etc/hosts.d'
      notify:
        - restart dnsmasq

    - name: Enable root server hostnames
      template: src=etc/hosts.d/root.j2
                dest=/etc/hosts.d/root
                owner=bin
                group=wheel
                mode=0644
      notify:
        - restart dnsmasq


    - name: Enable networks in /etc/networks
      template: src=etc/networks.j2
                dest=/etc/networks
                owner=bin
                group=wheel
                mode=0644

    - name: Localhost DNS in /etc/resolv.conf
      lineinfile: dest=/etc/resolv.conf
                  regexp='^nameserver 127.0.0.1'
                  insertbefore='^nameserver.*'
                  line='nameserver 127.0.0.1'

    - name: Localhost DNS for DHCP (${dhcp_interface})
      template: src=etc/dhcp/dhclient-${dhcp_interface}.conf.j2
                dest=/etc/dhcp/dhclient-${dhcp_interface}.conf
                owner=root
                group=root
      when_string: $dhcp_interface != ''


    - name: Start dnsmasq
      service: name=dnsmasq
               state=started
               enabled=yes

  handlers:
    - name: restart dnsmasq
      service: name=dnsmasq
               state=restarted
