# This play enables the DVD install repo as well as the EPEL sources
---
- hosts: all
  vars_files:
    - epel_vars.yml

  tasks:

  - name: Download EPEL repo
    get_url: url=${url}/${rpm} dest=/root

  - name: Install EPEL repo
    command: yum -y localinstall /root/${rpm}

