---
- hosts: all

  vars_files:
    - fail2ban_vars.yml
    - networks.yml

  tasks:
  - name: Install fail2ban
    yum: name=fail2ban
         state=installed
    tags:
      - packages

#  - name: Enable shorewall
#    lineinfile: dest=/etc/fail2ban/jail.conf
#                regexp='^banaction'
#                line='banaction = shorewall'
#                insertafter='^\[DEFAULT\]'
#    notify:
#      - Restart fail2ban
#    tags:
#      - config

  - name: Install /etc/fail2ban/jail.conf
    template: src=etc/fail2ban/jail.conf.j2
              dest=/etc/fail2ban/jail.conf
              owner=root
              group=root
              mode=0644
    notify:
      - Restart fail2ban
    tags:
      - config
      - jail

  - name: Set loglevel
    lineinfile: dest=/etc/fail2ban/fail2ban.conf
                regexp='^loglevel'
                line='loglevel=2'
    notify:
      - Restart fail2ban
    tags:
      - config

  - name: Enable fail2ban
    lineinfile: dest=/etc/shorewall/shorewall.conf
                regexp='^BLACKLISTNEWONLY'
                line='BLACKLISTNEWONLY=No'
    notify:
      - Restart shorewall
    tags:
      - config

  - name: Start fail2ban
    service: name=fail2ban
             state=restarted
             enabled=yes

  handlers:
    - name: Restart shorewall
      service: name=shorewall
               state=restarted

    - name: Restart fail2ban
      service: name=fail2ban
               state=restarted
