---
- hosts: all

  tasks:
  - name: Install shorewall
    yum: name=shorewall
         state=installed

#  - name: Restart rsyslog
#    service: name=rsyslog
#             state=restarted
#             enabled=yes
