#
# Ganglia cluster monitor
# 
---
- hosts: all

  vars_files:
    - ganglia_vars.yml
    - networks.yml
    - [ "vars/{{ ansible_os_family }}.yml", "vars/Defaults.yml" ]

  tasks:
  - name: Install topcoat header template
    template: src=usr/share/ganglia/templates/default/header.tpl.j2
              dest=/usr/share/ganglia/templates/default/header.tpl
              owner=root
              group=root
              backup=yes
