#
# Ganglia cluster monitor
#
---
- hosts: all

  vars_files:
    - ganglia_vars.yml
    - networks.yml

  tasks:
  - name: Install ganglia packages
    yum: name=$item
         state=installed
    with_items:
      - ganglia
      - ganglia-gmetad
      - ganglia-gmond
      - ganglia-gmond-python
      - ganglia-web
      - libnodeupdown-backend-ganglia
    tags:
      - packages

  - name: Download community python modules
    git: repo=$python_modules_git
         dest=$python_modules_dir
    tags:
      - modules

# TODO: ipmi monitoring

# TODO: multicast test and firewall
#  - name: Add multicast route
#    command: /sbin/route add -host ${mcast_addr} dev ${mcast_dev}

  - name: Ganglia monitor
    template: src=etc/ganglia/gmond.conf.j2
              dest=/etc/ganglia/gmond.conf
              owner=root
              group=root
              mode=0644
    notify:
      - Restart gmond
    tags:
      - config

  - name: Ganglia meta-data
    template: src=etc/ganglia/gmetad.conf.j2
              dest=/etc/ganglia/gmetad.conf
              owner=root
              group=root
              mode=0644
    notify:
      - Restart gmetad
    tags:
      - config

  - name: Disable tcpconn.pyconf
    template: src=etc/ganglia/conf.d/tcpconn.pyconf.j2
              dest=/etc/ganglia/conf.d/tcpconn.pyconf
              owner=root
              group=root
              mode=0644
    notify:
      - Restart gmond
    tags:
      - config

  - name: Enable Ganglia web interface
    template: src=etc/httpd/conf.d/ganglia.conf.j2
              dest=/etc/httpd/conf.d/ganglia.conf
              owner=root
              group=root
              mode=0644
    notify:
      - Restart httpd
    tags:
      - config

  - name: Enable motd service
    lineinfile: dest=/etc/services
                regexp="^gmond 8649/$item"
                line="gmond 8649/$item"
    with_items:
     - tcp
     - udp
    tags:
      - config
      - services

  - name: Enable gmetad-xml service
    lineinfile: dest=/etc/services
                regexp="^gmetad-xml 8651/$item"
                line="gmetad-xml 8651/$item"
    with_items:
     - tcp
     - udp
    tags:
      - config
      - services

  - name: Enable gmetad-int service
    lineinfile: dest=/etc/services
                regexp="^gmetad-int 8652/$item"
                line="gmetad-int 8652/$item"
    with_items:
     - tcp
     - udp
    tags:
      - config
      - services

  - name: Start gmond
    service: name=gmond
             state=started
             enabled=yes

  - name: Start gmetad
    service: name=gmetad
             state=started
             enabled=yes

  - name: Start HTTP
    service: name=httpd
             state=started
             enabled=yes


  handlers:
    - name: Restart gmond
      service: name=gmond
               state=restarted

    - name: Restart gmetad
      service: name=gmetad
               state=restarted

    - name: Restart httpd
      service: name=httpd
               state=restarted
