# Ganglia cluster monitor
---
- hosts: all

  vars_files:
    - ganglia_vars.yml
    - networks.yml

  tasks:
  - name: Install prerequisite packages
    yum: name=$item
         state=installed
    with_items:
      - ganglia
      - ganglia-gmetad
      - ganglia-gmond
      - ganglia-gmond-python
      - ganglia-web
      - libnodeupdown-backend-ganglia
    tags:
      - packages

  - name: Download community python modules
    git: repo=git://github.com/ganglia/gmond_python_modules.git
         dest=/root/gmond_python_modules

# TODO: ipmi monitoring

# TODO: multicast test and firewall
#  - name: Add multicast route
#    command: /sbin/route add -host ${mcast_addr} dev ${mcast_dev}

  - name: Ganglia monitor
    template: src=etc/ganglia/gmond.conf.j2
              dest=/etc/ganglia/gmond.conf
              owner=root
              group=root
              mode=0644

  - name: Ganglia meta-data
    template: src=etc/ganglia/gmetad.conf.j2
              dest=/etc/ganglia/gmetad.conf
              owner=root
              group=root
              mode=0644

  - name: Disable tcpconn.pyconf
    template: src=etc/ganglia/conf.d/tcpconn.pyconf.j2
              dest=/etc/ganglia/conf.d/tcpconn.pyconf
              owner=root
              group=root
              mode=0644

  - name: Restart gmond
    service: name=gmond
             state=restarted
             enabled=yes

  - name: Restart gmetad
    service: name=gmetad
             state=restarted
             enabled=yes

  - name: Allow HTTP connect
    seboolean: name=httpd_can_network_connect
               state=true
               persistent=yes

#  - name: Put HTTP in permissive mode
#    command: /usr/sbin/semanage permissive -a httpd_t

  - name: Allow networks
    template: src=etc/httpd/conf.d/ganglia.conf.j2
              dest=/etc/httpd/conf.d/ganglia.conf
              owner=root
              group=root
              mode=0644

  - name: Restart HTTP
    service: name=httpd
             state=restarted
             enabled=yes
