#
# Ganglia cluster monitor
#
# TODO: monitor cleanup mysql 
---
- hosts: all

  vars_files:
    - ganglia_vars.yml
    - networks.yml
    - [ "vars/{{ ansible_os_family }}.yml", "vars/Defaults.yml" ]

  tasks:
### REDHAT
  - name: Install ganglia packages
    yum: name=$item
         state=installed
    with_items:
      - ganglia
      - ganglia-gmetad
      - ganglia-gmond
      - ganglia-gmond-python
      - ganglia-web
      - libnodeupdown-backend-ganglia
    when: ansible_os_family == "RedHat"
    tags:
      - packages


### DEBIAN
  - name: Install ganglia packages
    apt: name=$item
         state=installed
    with_items:
      - ganglia-monitor
      - ganglia-monitor-python
      - ganglia-modules-linux
      - ganglia-webfrontend
      - gmetad
    when: ansible_os_family == "Debian"
    tags:
      - packages

### MODULES
  - name: Download community python modules
    git: repo=$python_modules_git
         dest=$python_modules_dir
    tags:
      - modules


### CONFIGURATION

# TODO: ipmi monitoring

# TODO: multicast test and firewall
#  - name: Add multicast route
#    command: /sbin/route add -host ${mcast_addr} dev ${mcast_dev}

  - name: Ganglia monitor
    template: src=etc/ganglia/gmond.conf.j2
              dest=/etc/ganglia/gmond.conf
              owner=root
              group=root
              mode=0644
    notify:
      - Restart {{service_gmond}}
    tags:
      - config

  - name: Ganglia meta-data
    template: src=etc/ganglia/gmetad.conf.j2
              dest=/etc/ganglia/gmetad.conf
              owner=root
              group=root
              mode=0644
    notify:
      - Restart gmetad
    tags:
      - config

  - name: Disable tcpconn.pyconf
    template: src=etc/ganglia/conf.d/tcpconn.pyconf.j2
              dest=/etc/ganglia/conf.d/tcpconn.pyconf
              owner=root
              group=root
              mode=0644
    notify:
      - Restart {{service_gmond}}
    tags:
      - config

  - name: Enable Ganglia web interface
    template: src=etc/httpd/conf.d/ganglia.conf.j2
              dest=/etc/{{service_httpd}}/conf.d/ganglia.conf
              owner=root
              group=root
              mode=0644
    notify:
      - Restart {{service_httpd}}
    tags:
      - config

  - name: Enable motd service
    lineinfile: dest=/etc/services
                regexp="^gmond 8649/$item"
                line="gmond 8649/$item"
    with_items:
     - tcp
     - udp
    tags:
      - config
      - services

  - name: Enable gmetad-xml service
    lineinfile: dest=/etc/services
                regexp="^gmetad-xml 8651/$item"
                line="gmetad-xml 8651/$item"
    with_items:
     - tcp
     - udp
    tags:
      - config
      - services

  - name: Enable gmetad-int service
    lineinfile: dest=/etc/services
                regexp="^gmetad-int 8652/$item"
                line="gmetad-int 8652/$item"
    with_items:
     - tcp
     - udp
    tags:
      - config
      - services

  - name: Start {{service_gmond}}
    service: name={{service_gmond}}
             state=started
             enabled=yes

  - name: Start gmetad
    service: name=gmetad
             state=started
             enabled=yes

  - name: Start HTTP
    service: name=httpd
             state=started
             enabled=yes


  handlers:
    - name: Restart {{service_gmond}}
      service: name={{service_gmond}}
               state=restarted

    - name: Restart gmetad
      service: name=gmetad
               state=restarted

    - name: Restart {{service_httpd}}
      service: name={{service_httpd}}
               state=restarted
