
---
- hosts: all

  tasks:

    - name: Enable SSL
      ini_file: dest=/etc/ajenti/ajenti.conf
                 section=ajenti
                 option=ssl
                 value=1
      tags:
        - config

    - name: Enable Globus key
      ini_file: dest=/etc/ajenti/ajenti.conf
                 section=ajenti
                 option=cert_key
                 value='/etc/grid-security/hostkey.pem'
      tags:
        - config

    - name: Enable Globus cert
      ini_file: dest=/etc/ajenti/ajenti.conf
                 section=ajenti
                 option=cert_file
                 value='/etc/grid-security/hostcert.pem'
      tags:
        - config

    - name: Set bind port
      ini_file: dest=/etc/ajenti/ajenti.conf
                 section=ajenti
                 option=bind_host
                 value={{ansible_eth0.ipv4.address}}
      tags:
        - config
