
# Format gluster disk:
# --extra-vars "format=yes"
# Mount gluster disk:
# --extra-vars "mount=yes"
---
- hosts: all

  vars_files:
    # - gluster_vars.yml
    - gluster_vars_ext4.yml

  tasks:

  - name: Set deadline I/O scheduler
    shell: /bin/echo "deadline" > /sys/block/${gluster_disk}/queue/scheduler
    tags:
      - tune

  - name: Set I/O request size
    shell: /bin/echo "256" > /sys/block/${gluster_disk}/queue/nr_requests
    tags:
      - tune

  - name: Set read-ahead size
    shell: /sbin/blockdev --setra 4096 /dev/${gluster_disk}
    tags:
      - tune


  - name: Unlimited stack size
    lineinfile: dest=/sbin/mount.glusterfs
                regexp='^ulimit -s unlimited'
                line='ulimit -s unlimited'
                insertbefore='^_init'
    tags:
      - limits

  - name: Unlimited lock size
    lineinfile: dest=/sbin/mount.glusterfs
                regexp='^ulimit -l unlimited'
                line='ulimit -l unlimited'
                insertbefore='^_init'
    tags:
      - limits

  - name: Unlimited CPU time
    lineinfile: dest=/sbin/mount.glusterfs
                regexp='^ulimit -t unlimited'
                line='ulimit -t unlimited'
                insertbefore='^_init'
    tags:
      - limits

  - name: Unlimited open files
    lineinfile: dest=/sbin/mount.glusterfs
                regexp='^ulimit -n unlimited'
                line='ulimit -n unlimited'
                insertbefore='^_init'
    tags:
      - limits

  - name: Mount Glusterfs
    mount: name=${common}
           src=127.0.0.1:/${volume}
           fstype=glusterfs
           opts=${fsopts},defaults,_netdev,acl,log-level=WARNING,log-file=/var/log/gluster.log
           state=mounted
    tags:
      - mount
