# This play enables rsyslog disables syslog and makes a basic configuration.
# All subsequent play should put configuration into /etc/rsyslog.d/ and
# notify reload rsyslog.
# Format gluster disk:
# --extra-vars "format=yes"
# Mount gluster disk:
# --extra-vars "mount=yes"
---
- hosts: all
  vars:
    is_format: "'$format' == 'yes'"
    is_mount: "'$mount' == 'yes'"

  vars_files:
    - gluster_vars.yml

  tasks:

  - name: Download Glusterfs repo
    get_url: url=${url}/${repo} dest=/etc/yum.repos.d/${repo}

  - name: Install Gluster server
    yum: name=glusterfs-server
         state=latest

  - name: Create Gluster partition
    lvol: vg=$vg_root
          lv=$lv_data
          size=$lv_size

  - name: Create XFS filesystem
    command: /sbin/mkfs.xfs -i size=512 /dev/${vg_root}/${lv_data}
    only_if: '$is_format'

  - name: Creat mount dir
    file: path=$lv_mnt
          state=directory

  - name: Create common dir
    file: path=$common
          state=directory

  - name: Mount Glusterfs
    mount: name=$lv_mnt
           src=/dev/${vg_root}/${lv_data}
           fstype=xfs
           state=mounted

  - name: Start Glusterfs
    service: name=glusterd
             state=started
             enabled=yes

# setfattr -x trusted.glusterfs.volume-id /data/glusterfs/common/brick1

  - name: Install Gluster bootstrap
    template: src=root/gluster_bootstrap.j2
              dest=/root/gluster_bootstrap
              owner=root
              group=root
              mode=0700
