#
# FAILED: gluster hangs
# wwmkchroot centos-6
# yum
# Running Transaction Test
#
# Format gluster disk:
# --extra-vars "format=yes"
# Mount gluster disk:
# --extra-vars "mount=yes"
---
- hosts: all
  vars_files:
    #- gluster_vars.yml
    - gluster_vars_ext4.yml

  vars:
    is_master: "'$inventory_hostname' == '$master'"
    is_format: "'$format' == 'yes'"
    is_mount: "'$mount' == 'yes'"

  tasks:

  - name: Download Glusterfs repo
    get_url: url=${url}/${repo} dest=/etc/yum.repos.d/${repo}
    tags:
      - packages

  - name: Install Gluster server
    yum: name=glusterfs-server
         state=latest
    tags:
      - packages

  - name: Create Gluster partition
    lvol: vg=$vg_root
          lv=$lv_data
          size=$lv_size
    tags:
      - partition

  - name: Create filesystem
    command: $fscreate /dev/${vg_root}/${lv_data}
    only_if: '$is_format'
    tags:
      - partition

  - name: Creat mount dir
    file: path=$lv_mnt
          state=directory
    tags:
      - partition

  - name: Create common dir
    file: path=$common
          state=directory
    tags:
      - partition

  - name: Mount Glusterfs
    mount: name=$lv_mnt
           src=/dev/${vg_root}/${lv_data}
           fstype=${fstype}
           state=mounted
    tags:
      - partition

  - name: Start Glusterfs
    service: name=glusterd
             state=started
             enabled=yes

# setfattr -x trusted.glusterfs.volume-id /data/glusterfs/common/brick1

  - name: Install Gluster bootstrap
    template: src=root/gluster_bootstrap.j2
              dest=/root/gluster_bootstrap_${fstype}
              owner=root
              group=root
              mode=0700
    ignore_errors: yes
    only_if: '$is_master'

# root-01> gluster peer probe root-03
# root-01> gluster volume add-brick common 10.1.1.3:/data/glusterfs/common/brick1
# root-01> gluster volume stop common
# root-01> gluster volume delete common

# lvremove /dev/vg_root/glusterfs_common_brick1
