# This play enables rsyslog disables syslog and makes a basic configuration.
# All subsequent play should put configuration into /etc/rsyslog.d/ and
# notify reload rsyslog.
# Format gluster disk:
# --extra-vars "format=yes"
# Mount gluster disk:
# --extra-vars "mount=yes"
---
- hosts: all

  vars_files:
    - gluster_vars.yml

  tasks:

  - name: Mount Glusterfs
    mount: name=/common
           src=127.0.0.1:/common
           fstype=glusterfs
           opts=acl,defaults,log-level=WARNING,log-file=/var/log/gluster.log
           state=mounted
    tags:
      - mount

  - name: Set deadline I/O scheduler
    shell: /bin/echo "deadline" > /sys/block/${gluster_disk}/queue/scheduler
    tags:
      - tune

  - name: Set I/O request size
    shell: /bin/echo "256" > /sys/block/${gluster_disk}/queue/nr_requests
    tags:
      - tune

  - name: Set read-ahead size
    shell: /sbin/blockdev --setra 4096 /dev/${gluster_disk}
    tags:
      - tune
