# Based on: https://gist.github.com/dillera/1634493
---
- hosts: all

  vars_files:
    - graphite_vars.yml

  tasks:
  - name: Install prerequisite packages
    yum: name=$item
         state=installed
    with_items:
      - pycairo
      - mod_python
      - Django
      - python-ldap
      - python-memcached
      - bitmap
      - bitmap-fonts
    tags:
      - packages

  - name: Install python pacakges
    pip: name=$item
         use_mirrors=no
    with_items:
      - django-tagging
      - twisted
      - txamqp
    tags:
      - packages

  - name: Download ${tgz_carbon}
    get_url: url=${url}/${tgz_carbon} dest=/root/${tgz_carbon}
    tags:
      - carbon

  - name: Uncompress ${tgz_carbon}
    shell: /bin/tar -C /root -xzf /root/${tgz_carbon}
    tags:
      - carbon

  - name: Install ${pkg_carbon}
    shell: cd /root/${pkg_carbon};python ./setup.py install
    tags:
      - carbon


  - name: Download ${tgz_whisper}
    get_url: url=${url}/${tgz_whisper} dest=/root/${tgz_whisper}
    tags:
      - whisper

  - name: Uncompress ${tgz_whisper}
    shell: /bin/tar -C /root -xzf /root/${tgz_whisper}
    tags:
      - whisper

  - name: Install ${pkg_whisper}
    shell: cd /root/${pkg_whisper};python ./setup.py install
    tags:
      - whisper


  - name: Download ${tgz_web}
    get_url: url=${url}/${tgz_web} dest=/root/${tgz_web}
    tags:
      - web

  - name: Uncompress ${tgz_web}
    shell: /bin/tar -C /root -xzf /root/${tgz_web}
    tags:
      - web

  - name: Check dependencies
    shell: cd /root/${pkg_web}; ./check-dependencies.py
    tags:
      - web

  - name: Install ${pkg_web}
    shell: cd /root/${pkg_web};python ./setup.py install
    tags:
      - web


  - name: Set directory modes on storage
    file: path=/opt/graphite/storage
          group=apache
          owner=apache
          recurse=yes
