#
# https://github.com/jaunesarmiento/fries/
#
---
- hosts: all

  vars_files:
    - networks.yml
    - [ "vars/{{ ansible_os_family }}.yml", "vars/Defaults.yml" ]

  tasks:
  - name: Download fries
    git: repo='git://github.com/jaunesarmiento/fries.git'
         dest=/opt/fries
    tags:
      - repo

  - name: Enable fries
    template: src=etc/httpd/conf.d/fries.conf.j2
              dest=/etc/{{service_httpd}}/conf.d/fries.conf
              owner=root
              group=root
              mode=0644
    notify:
      - Restart {{service_httpd}}
    tags:
      - config

  handlers:
    - name: Restart httpd
      service: name={{service_httpd}}
               state=restarted
