#
# Basic httpd settings
#
---
- hosts: all

  vars_files:
    - networks.yml
    - [ "vars/{{ ansible_os_family }}.yml", "vars/Defaults.yml" ]

  tasks:

  - name: Install /var/www/html/index.html
    template: src=var/www/html/index_home.html.j2
              dest=/var/www/html/index.html
              owner=root
              group=root
              mode=0644
    when: ansible_os_family == "RedHat"
    tags:
      - index
      - config

  - name: Install /var/www/index.html
    template: src=var/www/html/index_home.html.j2
              dest=/var/www/index.html
              owner=root
              group=root
              mode=0644
    when: ansible_os_family == "Debian"
    tags:
      - index
      - config
