# reinit:
# --extra-vars "reinit=yes"
---
- hosts: all

  vars_files:
    - inittab_vars.yml

  vars:
    is_reinit: "'$reinit' == 'yes'"

  tasks:
### REDHAT
  - name: Install packages
    yum: name=$item
         state=installed
    with_items:
      - htop
      - sysstat
    when: ansible_os_family == "RedHat"
    tags:
      - packages

### DEBIAN
  - name: Install packages
    apt: name=$item
         state=installed
    with_items:
      - htop
      - sysstat
    when: ansible_os_family == "Debian"
    tags:
      - packages

  - name: Ubuntu Warning
    debug: msg="Ubuntu's init is a fuckin mess!"
    when: ansible_os_family == "Debian"

### CONFIGURATION
  - name: Set ttys
    lineinfile: dest=/etc/sysconfig/init
                regexp='^ACTIVE_CONSOLES'
                line='ACTIVE_CONSOLES=/dev/tty[7-8]'
    when: ansible_os_family == "RedHat"
    tags:
      - tty

  - name: Set X tty
    lineinfile: dest=/etc/init/start-ttys.conf
                regexp='^env X_TTY'
                line='env X_TTY=/dev/tty8'
    when: ansible_os_family == "RedHat"
    tags:
      - tty

  - name: Install Init start-messages
    template: src=etc/init/start-messages.conf.j2
              dest=/etc/init/start-messages.conf
              owner=root
              group=root
              mode=0640
    when: ansible_os_family == "RedHat"
    tags:
      - messages

  - name: Install Init messages
    template: src=etc/init/messages.conf.j2
              dest=/etc/init/messages.conf
              owner=root
              group=root
              mode=0640
    when: ansible_os_family == "RedHat"
    tags:
      - messages

  - name: Install Init start-top
    template: src=etc/init/start-top.conf.j2
              dest=/etc/init/start-top.conf
              owner=root
              group=root
              mode=0640
    when: ansible_os_family == "RedHat"
    tags:
      - top

  - name: Install Init top
    template: src=etc/init/top.conf.j2
              dest=/etc/init/top.conf
              owner=root
              group=root
              mode=0640
    when: ansible_os_family == "RedHat"
    tags:
      - top

  - name: Install Init start-top-mem
    template: src=etc/init/start-top-mem.conf.j2
              dest=/etc/init/start-top-mem.conf
              owner=root
              group=root
              mode=0640
    when: ansible_os_family == "RedHat"
    tags:
      - top

  - name: Install Init top-mem
    template: src=etc/init/top-mem.conf.j2
              dest=/etc/init/top-mem.conf
              owner=root
              group=root
              mode=0640
    when: ansible_os_family == "RedHat"
    tags:
      - top

  - name: Install Init start-iostat
    template: src=etc/init/start-iostat.conf.j2
              dest=/etc/init/start-iostat.conf
              owner=root
              group=root
              mode=0640
    when: ansible_os_family == "RedHat"
    tags:
      - iostat

  - name: Install Init iostat
    template: src=etc/init/iostat.conf.j2
              dest=/etc/init/iostat.conf
              owner=root
              group=root
              mode=0640
    when: ansible_os_family == "RedHat"
    tags:
      - iostat

  - name: Install Init start-mpstat
    template: src=etc/init/start-mpstat.conf.j2
              dest=/etc/init/start-mpstat.conf
              owner=root
              group=root
              mode=0640
    when: ansible_os_family == "RedHat"
    tags:
      - mpstat

  - name: Install Init mpstat
    template: src=etc/init/mpstat.conf.j2
              dest=/etc/init/mpstat.conf
              owner=root
              group=root
              mode=0640
    when: ansible_os_family == "RedHat"
    tags:
      - mpstat

  - name: Install Init start-gstat
    template: src=etc/init/start-gstat.conf.j2
              dest=/etc/init/start-gstat.conf
              owner=root
              group=root
              mode=0640
    when: ansible_os_family == "RedHat"
    tags:
      - gstat

  - name: Install Init gstat
    template: src=etc/init/gstat.conf.j2
              dest=/etc/init/gstat.conf
              owner=root
              group=root
              mode=0640
    when: ansible_os_family == "RedHat"
    tags:
      - gstat

  - name: Install /root/bin/reinit
    template: src=root/bin/${item}.j2
              dest=/root/bin/${item}
              owner=root
              group=root
              mode=0755
    with_items:
      - reinit

# TODO: tcptrack external

  - name: Restart init
    shell: /sbin/telinit q
    when: ansible_os_family == "RedHat"

  - name: Reinit
    command: /root/bin/reinit
    only_if: '$is_reinit'
