#
# https://help.ubuntu.com/13.04/serverguide/openldap-server.html
#
---
- hosts: all
  vars_files:
    - ldap_vars.yml

  tasks:
    - name: Install ldap packages
      yum: name=$item
           state=installed
      with_items:
        - openldap-servers
        - openldap-clients
        - python-ldap
      when: ansible_os_family == "RedHat"
      tags:
        - packages

    - name: Create ldif directory
      file: path=/root/ldif
            state=directory
      tags:
        - directories

    - name: Install base.ldif
      template: src=root/ldif/base.ldif.j2
                dest=/root/ldif/base.ldif
      tags:
        - config

    - name: olcSuffix
      lineinfile: 'dest={{ldap.database}} regexp="^olcSuffix" line="olcSuffix: {{ldap.domain}}"'
      tags:
        - domain
        - config

    - name: olcRootDN
      lineinfile: 'dest={{ldap.database}} regexp="^olcRootDN" line="olcRootDN: cn=Manager,{{ldap.domain}}"'
      tags:
        - domain
        - config

    - name: olcRootPW
      lineinfile: 'dest={{ldap.database}} regexp="^olcRootPW" insertafter="^olcRootDN" line="olcRootPW: {{ldap.password}}"'
      tags:
        - domain
        - config

    - name: Start ldap server
      service: name=slapd
               state=started
               enabled=yes
