#
# https://help.ubuntu.com/13.04/serverguide/openldap-server.html
#
---
- hosts: all
  vars_files:
    - networks.yml
    - ldap_vars.yml
    - [ "vars/{{ ansible_os_family }}.yml", "vars/Defaults.yml" ]

  tasks:
    - name: Install ldap tools
      template: src=root/bin/${item}.j2
                dest=/root/bin/${item}
                owner=root
                group=root
                mode=0755
      with_items:
        - ldap_config
        - ldap_modify
        - ldap_add

    - name: Install packages
      yum: name=$item
           state=installed
      with_items:
        - phpldapadmin
      when: ansible_os_family == "RedHat"
      notify:
        - Restart httpd
      tags:
        - packages

    - name: Enable phpldapadmin
      template: src=etc/{{service_httpd}}/conf.d/phpldapadmin.conf.j2
              dest=/etc/{{service_httpd}}/conf.d/phpldapadmin.conf
              owner=root
              group=root
              mode=0644
      notify:
        - Restart httpd

  handlers:
    - name: Restart httpd
      service: name={{service_httpd}}
               state=restarted
