# This play modifies /etc/login.defs
---
- hosts: all

  tasks:
    - name: Umask 007
      lineinfile: dest=/etc/login.defs
                  state=present
                  regexp="^UMASK"
                  line="UMASK 007"
                  backup=yes
      tags:
        - config
