# This play modifies /etc/login.defs
---
- hosts: all

  tasks:
    - name: Secure su
      lineinfile: dest=/etc/login.defs
                  state=present
                  regexp="^UMASK"
                  line="UMASK 007"
      tags:
        - config
