# Based on: http://edin.no-ip.com/blog/hswong3i/mariadb-galera-mastermaster-replication-ubuntu-12-04-howto
---
- hosts: all

  vars_files:
    - networks.yml
    - mariadb_vars.yml

  vars:
    is_master: "'$inventory_hostname' == '$master'"

  tasks:
# set root password
# https://coderwall.com/p/yez9yw?i=1&p=2&q=sort%3Ascore+desc&t%5B%5D=ansible
  - name: Install MySQL-python
    yum: name=MySQL-python
         state=installed
    when: ansible_os_family == "RedHat"
    tags:
      - packages

  - name: Install MySQL-python
    apt: name=python-mysqldb
         state=installed
    when: ansible_os_family == "Debian"
    tags:
      - packages

  - name: Update mysql root password for all root accounts
    mysql_user: name=root
                password={{mariadb.password}}
                login_password=''
                login_user=root
                login_unix_socket={{mariadb.socket}}
    only_if: '$is_master'

  - name: Remove the test database
    mysql_db: name=test
              state=absent
              login_user=root
              login_password={{mariadb.password}}
              login_unix_socket={{mariadb.socket}}
    only_if: '$is_master'

    tags:
      - init
