---
- hosts: all

  vars_files:
    - networks.yml
    - mariadb_vars.yml
    - [ "vars/{{ ansible_os_family }}.yml", "vars/Defaults.yml" ]

  tasks:
    - name: Install packages
      yum: name=$item
           state=installed
      with_items:
        - mytop
        - mtop
        - innotop
        - php-mcrypt
        - php-mbstring
        - phpmyadmin
      when: ansible_os_family == "RedHat"
      notify:
        - Restart httpd
      tags:
        - packages

# https://github.com/repoforge/rpms/issues/254
    - name: Fix php-mcrypt
      lineinfile: dest=/etc/php.d/mcrypt.ini
                  regexp='^extension'
                  line='extension=mcrypt.so'
      when: ansible_os_family == "RedHat"
      notify:
        - Restart httpd
      tags:
        - fix

    - name: Enable phpmyadmin
      template: src=etc/{{service_httpd}}/conf.d/phpmyadmin.conf.j2
              dest=/etc/{{service_httpd}}/conf.d/phpmyadmin.conf
              owner=root
              group=root
              mode=0644
      notify:
        - Restart httpd

    - name: Install phpmyadmin config
      template: src=usr/share/phpmyadmin/config.inc.php.j2
              dest=/usr/share/phpmyadmin/config.inc.php
              owner=root
              group=root
              mode=0644

    - name: Create /root/bin directory
      file: path=/root/bin
            owner=root
            group=root
            state=directory

    - name: Install wsrep_status
      template: src=root/bin/wsrep_status.j2
                dest=/root/bin/wsrep_status
                owner=root
                group=root
                mode=0755

    - name: Install mytop
      template: src=root/bin/mytop.j2
                dest=/root/bin/mytop
                owner=root
                group=root
                mode=0755

    - name: Install mtop
      template: src=root/bin/mtop.j2
                dest=/root/bin/mtop
                owner=root
                group=root
                mode=0755

    - name: Install innotop
      template: src=root/bin/innotop.j2
                dest=/root/bin/innotop
                owner=root
                group=root
                mode=0755

  handlers:
    - name: Restart httpd
      service: name={{service_httpd}}
               state=restarted
