# Based on: http://edin.no-ip.com/blog/hswong3i/mariadb-galera-mastermaster-replication-ubuntu-12-04-howto
# http://samlambert.com/posts/galera-load-balancer-rpms/
# http://www.fromdual.com/mysql-and-galera-load-balancer
---
- hosts: all

  vars_files:
    - mariadb_vars.yml

  tasks:

  - name: Download GLB
    get_url: url=${mariadb.glb_url}/${mariadb.glb_rpm} dest=/root
    tags:
      - packages

  - name: Install GLB
    command: yum -y localinstall /root/${mariadb.glb_rpm}
    tags:
      - packages

  - name: Install nc
    yum: name=nc
         state=installed
    tags:
      - packages

  - name: Install /etc/sysconfig/glbd
    template: src=etc/sysconfig/glbd.j2
              dest=/etc/sysconfig/glbd
              owner=root
              group=root
              mode=0644
    notify:
      - Restart glbd
    tags:
      - config

# TODO: pid detection and status
  - name: Install /etc/init.d/glbd
    template: src=etc/init.d/glbd.j2
              dest=/etc/init.d/glbd
              owner=root
              group=root
              mode=0755
    notify:
      - Restart glbd
    tags:
      - config

  - name: Start glbd
    service: name=glbd
             state=started
             enabled=yes

  handlers:
    - name: Restart glbd
      service: name=glbd
               state=restarted
