# Based on: http://edin.no-ip.com/blog/hswong3i/mariadb-galera-mastermaster-replication-ubuntu-12-04-howto
---
- hosts: all

  vars_files:
    - mariadb_vars.yml

  tasks:
  - name: Install MariaDB Repo
    template: src=etc/yum.repos.d/MariaDB.repo.j2
              dest=/etc/yum.repos.d/MariaDB.repo
              owner=root
              group=root
              mode=0644

#  - name: Uninstall mysql-libs
#    yum: name=mysql-libs
#         state=absent
#    ignore_errors: yes

  - name: Install MariaDB packages
    yum: name=$item
         state=installed
    with_items:
      - MariaDB-Galera-server
      - MariaDB-client
      - MariaDB-server
      - MariaDB-shared
      - MariaDB-compat
      - galera
    tags:
      - packages

  - name: Set service timeout
    lineinfile: dest=/etc/init.d/mysql
                regexp="^service_startup_timeout"
                line="service_startup_timeout=${timeout}"

  - name: Setup /etc/my.cnf
    template: src=etc/my.cnf.j2
              dest=/etc/my.cnf
              owner=root
              group=root
              mode=0644
    notify:
      - Restart mysqld

  - name: Setup /etc/my.cnf.d/server.cnf
    template: src=etc/my.cnf.d/server.cnf.j2
              dest=/etc/my.cnf.d/server.cnf
              owner=root
              group=root
              mode=0644
    notify:
      - Restart mysqld

  - name: Setup PHP mysql socket
    lineinfile: dest=/etc/php.ini
                regexp="^mysql.default_socket"
                line="mysql.default_socket = ${socket}"
    notify:
      - Restart httpd

  - name: Setup PHP mysqli socket
    lineinfile: dest=/etc/php.ini
                regexp="^mysqli.default_socket"
                line="mysqli.default_socket = ${socket}"
    notify:
      - Restart httpd

  - name: Start mysqld
    service: name=mysql
             state=started
             enabled=yes

  handlers:
    - name: Restart mysqld
      service: name=mysql
               state=restarted

    - name: Restart httpd
      service: name=httpd
               state=restarted


# mysql -e "SET wsrep_on = OFF; DELETE FROM mysql.user WHERE user = '';"
# mysql -e "SET wsrep_on = OFF; GRANT ALL ON *.* TO 'root'@'%' IDENTIFIED BY 'password';"
# mysql -e "SHOW STATUS LIKE 'wsrep_%';"
