# Based on: http://edin.no-ip.com/blog/hswong3i/mariadb-galera-mastermaster-replication-ubuntu-12-04-howto
---
- hosts: all

  vars_files:
    - mariadb_vars.yml
    - [ "vars/{{ ansible_os_family }}.yml", "vars/Defaults.yml" ]

  tasks:

    - name: Remove Galera State
      file: path={{mariadb.state}}
            state=absent
      notify:
        - Restart mysql
      tags:
        - reset

  handlers:
    - name: Restart mysql
      service: name={{service_mysql}}
               state=restarted


# mysql -e "SET wsrep_on = OFF; DELETE FROM mysql.user WHERE user = '';"
# mysql -e "SET wsrep_on = OFF; GRANT ALL ON *.* TO 'root'@'%' IDENTIFIED BY 'password';"
# mysql -e "SHOW STATUS LIKE 'wsrep_%';"
