# Format gluster disk:
# --extra-vars "format=yes"
---
- hosts: all
  vars:
    is_format: "'$format' == 'yes'"

  vars_files:
    - mongodb_vars.yml
    - graylog2_vars.yml

  tasks:
  - name: Install 10Gen Repo
    template: src=etc/yum.repos.d/10gen.repo.j2
              dest=/etc/yum.repos.d/10gen.repo
              owner=root
              group=root
              mode=0644

#  - name: Uninstall mongodb
#    yum: name=mongodb
#         state=absent

  - name: Install mongo-10gen
    yum: name=mongo-10gen
         state=installed

  - name: Install mongo-10gen-server
    yum: name=mongo-10gen-server
         state=installed

  - name: Uninstall pymongo
    yum: name=pymongo
         state=absent

  - name: Install python-pip
    yum: name=python-pip
         state=installed

  - name: Install gcc
    yum: name=gcc
         state=installed

  - name: Install python-devel
    yum: name=python-devel
         state=installed

  - name: PIP Install pymongo
    pip: name=pymongo
         use_mirrors=no
         state=latest

  - name: Stop mongodb
    service: name=mongod
             state=stopped

  - name: Create Mongo partition
    lvol: vg=$vg_root
          lv=$lv_data
          size=$lv_size

  - name: Create XFS filesystem
    command: /sbin/mkfs.xfs -i size=512 /dev/${vg_root}/${lv_data}
    only_if: '$is_format'

  - name: Creat mount dir
    file: path=$lv_mnt
          owner=mongod
          group=mongod
          state=directory

  - name: Mount Mongo partition
    mount: name=$lv_mnt
           src=/dev/${vg_root}/${lv_data}
           fstype=xfs
           state=mounted

  - name: Set mongodb
    lineinfile: dest=/etc/mongod.conf 
                regexp='^dbpath'
                line="dbpath=${lv_mnt}"

  - name: Start mongod
    service: name=mongod
             state=started

  - name: Create admin user
    mongodb_user: database=admin
                  name=${admin_user}
                  password=${admin_user}
                  state=present

  - name: Create graylog user
    mongodb_user: database=graylog2
                  name=${graylog_user}
                  password=${graylog_user}
                  state=present
