# This play installs nodejs and supervisor
---
- hosts: all
  vars_files:
    - epel_vars.yml

  tasks:

  - name: Download Hornos CentOS repo
    get_url: url=${hornos_url}
             dest=/etc/yum.repos.d/hornos.repo
             owner=root
             group=root

  - name: Install node.js
    yum: name=nodejs
         state=installed

  - name: Install supervisor
    yum: name=supervisor
         state=installed

  - name: Start supervisord
    service: name=supervisord
             state=started
             enabled=yes

