# This play installs nodejs and supervisor
---
- hosts: all

  tasks:
    - name: Install prerequisite packages
      yum: name=$item
           state=installed
      with_items:
        - nodejs
      tags:
        - packages

    - name: Install nvm package manager
      git: repo=git://github.com/creationix/nvm.git
           dest=/opt/nvm

    - name: Install /etc/profile.d/nvm.sh
      template: src=etc/profile.d/nvm.sh.j2
                dest=/etc/profile.d/nvm.sh
