# This play installs nodejs and supervisor
---
- hosts: all
  vars_files:
    - epel_vars.yml

  tasks:

  - name: Download Hornos CentOS repo
    get_url: url=${hornos_url}
             dest=/etc/yum.repos.d/hornos.repo
             owner=root
             group=root

  - name: Install prerequisite packages
    yum: name=$item
         state=installed
    with_items:
      - nodejs
      - nodejs-devel
      - v8
      - v8-devel
      - supervisor
    tags:
      - packages

  - name: Start supervisord
    service: name=supervisord
             state=started
             enabled=yes

