# This play modifies
# http://www.ntp.org/ntpfaq/NTP-s-config-adv.htm
#
# --extra-vars "bcast=yes"
#
---
- hosts: all

  vars_files:
    - networks.yml
    - [ "vars/{{ansible_os_family}}.yml", "vars/Defaults.yml" ]

  vars:
    is_bcast: "'$bcast' == 'yes'"

  tasks:
    - name: Install NTP Server
      yum: name=ntp
           state=installed
      when: ansible_os_family == "RedHat"
      tags:
        - packages

    - name: Install NTP Server
      apt: name=ntp
           state=installed
      when: ansible_os_family == "Debian"
      tags:
        - packages


    - name: Start ntpd
      service: name={{service_ntpd}}
               state=started
               enabled=yes

  handlers:
    - name: Restart ntpd
      service: name={{service_ntpd}}
               state=restarted
