# This play modifies
# http://www.ntp.org/ntpfaq/NTP-s-config-adv.htm
---
- hosts: all

  vars_files:
    - networks.yml
    - [ "vars/{{ansible_os_family}}.yml", "vars/Defaults.yml" ]

  tasks:
    - name: Install NTP Server
      yum: name=ntp
           state=installed
      when: ansible_os_family == "RedHat"
      tags:
        - packages

    - name: Install NTP Server
      apt: name=ntp
           state=installed
      when: ansible_os_family == "Debian"
      tags:
        - packages

    - name: Setup NTP Server
      lineinfile: dest=/etc/ntp.conf
                  state=present
                  regexp="^broadcast .* autokey version 4"
                  insertafter="# broadcast server"
                  line="broadcast ${broadcasts.system} autokey version 4"
      notify:
        - Restart ntpd
      tags:
        - configs

    - name: Start ntpd
      service: name={{service_ntpd}}
               state=started
               enabled=yes

  handlers:
    - name: Restart ntpd
      service: name={{service_ntpd}}
               state=restarted
