#
# https://www.overclockers.com/forums/showthread.php?t=726947
# https://help.ubuntu.com/13.04/serverguide/openldap-server.html
# http://itdavid.blogspot.hu/2012/05/howto-openldap-2.html
#
# TODO: DB_CONFIG tuning
#
---
- hosts: all

  vars_files:
    - networks.yml
    - openldap_vars.yml

  tasks:
### PACKAGES
    - name: Install ldap packages
      yum: name=$item
           state=installed
      with_items:
        - openldap-servers
        - openldap-clients
        - python-ldap
      when: ansible_os_family == "RedHat"
      tags:
        - packages

### CONFIGURATION
    - name: Set olcSuffix
      lineinfile: 'dest={{ldap.database}} regexp="^olcSuffix" line="olcSuffix: {{ldap.domain}}"'
      tags:
        - domain
        - config

    - name: Set olcRootDN
      lineinfile: 'dest={{ldap.database}} regexp="^olcRootDN" line="olcRootDN: {{ldap.manager}}"'
      tags:
        - domain
        - config

    - name: Set olcRootPW
      lineinfile: 'dest={{ldap.database}} regexp="^olcRootPW" insertafter="^olcRootDN" line="olcRootPW: {{ldap.password}}"'
      tags:
        - domain
        - config

    - name: Set monitor auth
      lineinfile: 'dest={{ldap.monitor}} regexp="l,cn=auth" line=" l,cn=auth\" read by dn.base=\"${ldap.manager}\" read by * none"'
      tags:
        - domain
        - config

    - name: Start LDAP server
      service: name=slapd
               state=started
               enabled=yes

    - name: Install basic ldifs
      template: src=etc/openldap/${item}.j2
                dest=/etc/openldap/${item}
      with_items:
        - base.ldif
        - test.ldif
      tags:
        - config
        - ldif

    - name: Load base.ldif
      command: '/usr/bin/ldapadd -f /etc/openldap/base.ldif -x -D "${ldap.manager}" -w ${ldap.password_plain}'
      ignore_errors: yes
      tags:
        - config
        - ldif

    - name: Load test.ldif
      command: '/usr/bin/ldapadd -f /etc/openldap/test.ldif -x -D "${ldap.manager}" -w ${ldap.password_plain}'
      ignore_errors: yes
      tags:
        - config
        - ldif
