#
# http://openstack.griddynamics.com/setup_single.html
#
---
- hosts: all

  tasks:

### REDHAT
  - name: Install umask repo
    template: src=etc/yum.repos.d/umask.repo.j2
              dest=/etc/yum.repos.d/umask.repo
              owner=root
              group=root
    when: ansible_os_family == "RedHat"
    tags:
      - repo
      - packages

  - name: Install syslog-ng packages
    yum: name=syslog-ng
         state=latest
         enablerepo=umask
    when: ansible_os_family == "RedHat"
    tags:
      - packages

  - name: Install syslog-ng-libdbi packages
    yum: name=syslog-ng-libdbi
         state=latest
         enablerepo=umask
    when: ansible_os_family == "RedHat"
    tags:
      - packages
