#
# https://help.ubuntu.com/13.04/serverguide/openldap-server.html
#
---
- hosts: all
  vars_files:
    - networks.yml
    - openldap_vars.yml
    - [ "vars/{{ ansible_os_family }}.yml", "vars/Defaults.yml" ]

  tasks:
    - name: Install LDAP tools
      template: src=root/bin/${item}.j2
                dest=/root/bin/${item}
                owner=root
                group=root
                mode=0755
      with_items:
        - ldap_config
        - ldap_modify
        - ldap_search
        - ldap_add
      tags:
        - packages

### REDHAT
    - name: Install packages
      yum: name=$item
           state=installed
      with_items:
        - phpldapadmin
      when: ansible_os_family == "RedHat"
      notify:
        - Restart httpd
      tags:
        - packages

### DEBIAN
    - name: Install packages
      apt: name=$item
           state=installed
      with_items:
        - phpldapadmin
      when: ansible_os_family == "Debian"
      notify:
        - Restart httpd
      tags:
        - packages


    - name: Install phpldapadmin config
      template: src=etc/phpldapadmin/config.php.j2
              dest=/etc/phpldapadmin/config.php
              owner=root
              group=root
              mode=0644
              backup=yes
      tags:
        - config

    - name: Enable phpldapadmin
      template: src=etc/httpd/conf.d/phpldapadmin.conf.j2
              dest=/etc/{{service_httpd}}/conf.d/phpldapadmin.conf
              owner=root
              group=root
              mode=0644
      notify:
        - Restart httpd

  handlers:
    - name: Restart httpd
      service: name={{service_httpd}}
               state=restarted
