#
# http://oss.sgi.com/projects/pcp/
#
---
- hosts: all

  tasks:
### REDHAT
  - name: Install PCP packages
    yum: name=$item
         state=installed
    with_items:
      - pcp
      - pcp-gui
      - python-pcp
      - perl-PCP-PMDA
      - perl-PCP-MMV
      - perl-PCP-LogSummary
      - perl-PCP-LogImport
      - pcp-import-sar2pcp
      - pcp-import-mrtg2pcp
      - pcp-import-iostat2pcp
    when: ansible_os_family == "RedHat"
    tags:
      - packages

### DEBIAN
  - name: Install PCP packages
    apt: name=$item
         state=installed
    with_items:
      - pcp
      - pcp-gui
      - pcp-import-sar2pcp
      - pcp-import-mrtg2pcp
      - pcp-import-iostat2pcp
    when: ansible_os_family == "Debian"
    tags:
      - packages

  - name: Start pmcd
    service: name=pmcd
             state=started
             enabled=yes
