# This play enables rsyslog disables syslog and makes a basic configuration.
# All subsequent play should put configuration into /etc/rsyslog.d/ and
# notify reload rsyslog.
# Format gluster disk:
# --extra-vars "format=yes"
# Mount gluster disk:
# --extra-vars "mount=yes"
---
- hosts: all

  vars_files:
    - rabbitmq_vars.yml

  tasks:

  - name: Download Erlang repo
    get_url: url=${url}/${repo}
             dest=/etc/yum.repos.d/${repo}

  - name: Abort
    file: path=/etc/yum.repos.d/${repo}
          state=absent

  - fail: msg=Repo Abort

  - name: Install Erlang
    yum: name=erlang
         state=latest

  - name: Download rabbitmq-server
    get_url: url=${rpm_url}/${rpm} dest=/root

# purge epel version
#  - name: Uninstall rabbitmq-server
#    yum: name=rabbitmq-server
#         state=absent

  - name: Install rabbitmq-server
    command: yum -y localinstall /root/${rpm}

  - name: Start rabbitmq-server
    service: name=rabbitmq-server
             state=started
             enabled=yes
