
---
- hosts: all

  vars_files:
    - rabbitmq_vars.yml

  tasks:

  - name: Download Erlang repo
    get_url: url={{ url }}/{{ repo }}
             dest=/etc/yum.repos.d/{{ repo }}
    tags:
      - repo

  - name: Install Erlang repo key
    shell: /bin/rpm --import {{ key }}
    tags:
      - repo

  - name: Install Erlang
    yum: name=erlang
         state=latest
    tags:
      - packages

  - name: Download rabbitmq-server
    get_url: url={{ rpm_url }}/{{ rpm }} dest=/root
    tags:
      - packages

  - name: Install rabbitmq key
    shell: /bin/rpm --import {{ rpm_key }}
    tags:
      - packages

# purge epel version
#  - name: Uninstall rabbitmq-server
#    yum: name=rabbitmq-server
#         state=absent

  - name: Install rabbitmq-server
    command: yum -y localinstall /root/{{ rpm }}
    tags:
      - packages

  - name: Start rabbitmq-server
    service: name=rabbitmq-server
             state=started
             enabled=yes
