
---
- hosts: all

  vars_files:
    - networks.yml
    - [ "vars/{{ ansible_os_family }}.yml", "vars/Defaults.yml" ]

  tasks:

  - name: Install Redis
    when: ansible_os_family == "RedHat"
    yum: name=redis
         state=installed
    tags:
      - packages

  - name: Install Redis
    when: ansible_os_family == "Debian"
    apt: name=$item
         state=installed
    with_items:
      - redis-server
      - python-redis
      - python-celery
    tags:
      - packages

  - name: Start redis
    service: name={{service_httpd}}
             state=started
             enabled=yes
