# This play enables the DVD install repo as well as the EPEL sources
---
- hosts: all
  vars_files:
    - repo_vars.yml

  tasks:

  - name: Download EPEL repo
    get_url: url=${epel_url}/${epel_rpm} dest=/root

  - name: Install EPEL repo
    command: rpm -Uvh /root/${epel_rpm}
    ignore_errors: yes
