# Enable EPEL repo
---
- hosts: all
  vars_files:
    - repo_epel_vars.yml

  tasks:

  - name: Download EPEL repo
    get_url: url=${url}/${rpm} dest=/root
    when: ansible_os_family == "RedHat"
    tags:
      - packages

  - name: Install EPEL repo
    command: yum -y localinstall /root/${rpm}
    when: ansible_os_family == "RedHat"
    tags:
      - packages
