---
- hosts: all
  vars_files:
    - repo_hornos_vars.yml

  tasks:

  - name: Download hornos repo
    get_url: url=${url}/${repo} dest=/etc/yum.repos.d/${repo}
    when: ansible_os_family == "RedHat"
    tags:
      - packages
