# Enable rpmforge repo
---
- hosts: all
  vars_files:
    - repo_rpmforge_vars.yml

  tasks:

  - name: Download rpmforge repo
    get_url: url=${url}/${rpm} dest=/root
    when: ansible_os_family == "RedHat"
    tags:
      - packages

  - name: Install rpmforge repo
    when: ansible_os_family == "RedHat"
    command: yum -y localinstall /root/${rpm}
    tags:
      - packages
