# Enable rpmforge repo
---
- hosts: all
  vars_files:
    - rpmforge_vars.yml

  tasks:

  - name: Download rpmforge repo
    get_url: url=${url}/${rpm} dest=/root
    tags:
      - packages

  - name: Install rpmforge repo
    command: yum -y localinstall /root/${rpm}
    tags:
      - packages
