# This play enables rsyslog server on TCP 514 and notifies rsyslog to reload
---
- hosts: all

  tasks:
  - name: Enable rsyslog server
    template: src=etc/rsyslog.d/10-loghost.conf.j2
              dest=/etc/rsyslog.d/10-loghost.conf
              owner=root
              group=root
              mode=0644

  - name: Self logging
    template: src=etc/rsyslog.d/99-finish.conf.j2
              dest=/etc/rsyslog.d/99-finish.conf
              owner=root
              group=root
              mode=0644

  - name: restart rsyslog
    service: name=rsyslog
             state=restarted
