# This play secures the server
# Based on RH EAL4+ recommenadtions
---
- name: Secure the server
  hosts: all

- include: ssh_server.yml
- include: su.yml
- include: login_defs.yml
- include: entropy.yml
