
---
- hosts: all

  vars_files:
    - networks.yml
    - rabbitmq_vars.yml
    - sensu_vars.yml
    - [ "vars/{{ ansible_os_family }}.yml", "vars/Defaults.yml" ]

  vars:
    is_master: "'$inventory_hostname' == '$master'"

  tasks:

### REDHAT
    - name: Install Sensu Repo
      template: src=etc/yum.repos.d/sensu.repo.j2
                dest=/etc/yum.repos.d/sensu.repo
                owner=root
                group=root
                mode=0644
      when: ansible_os_family == "RedHat"
      tags:
        - repo

    - name: Install packages
      when: ansible_os_family == "RedHat"
      yum: name=sensu
           state=installed
           enablerepo=sensu
      tags:
        - packages

    - name: Create sensu vhost
      rabbitmq_vhost: name=/sensu
                      state=present
      tags:
        - config

    - name: Create sensu user
      rabbitmq_user: user={{sensu.user}}
                     password={{sensu.password}}
                     vhost=/sensu
                     configure_priv=.*
                     read_priv=.*
                     write_priv=.*
                     state=present
      tags:
        - config

    - name: Install /etc/sensu/config.json
      template: src=etc/sensu/config.json.j2
                dest=/etc/sensu/config.json
                owner=root
                group=root
                mode=0644
      tags:
        - config

    - name: Start sensu services
      service: name=$item
               state=started
      with_items:
        - sensu-server
        - sensu-api
        - sensu-client
        - sensu-dashboard
