#
# Shorewall firewall
#
# TODO: dhcp from networks.yml
---
- hosts: all

  vars_files:
    - networks.yml

  tasks:
  - name: Install shorewall
    yum: name=shorewall
         state=installed
    when: ansible_os_family == "RedHat"
    tags:
      - packages

  - name: Install shorewall
    apt: name=shorewall
         state=installed
    when: ansible_os_family == "Debian"
    tags:
      - packages

### PARAMETERS
  - name: Install params
    template: src=etc/shorewall/params.j2
              dest=/etc/shorewall/params
              owner=root
              group=root
              mode=0640
              backup=yes
    tags:
      - parameters
    notify:
      - Restart shorewall

### ZONES
  - name: Create /etc/shorewall/zones.d
    file: path=/etc/shorewall/zones.d
          owner=root
          group=root
          state=directory
    tags:
      - zones

  - name: Install /etc/shorewall/zones.d/root
    template: src=etc/shorewall/zones.d/home.j2
              dest=/etc/shorewall/zones.d/root
              owner=root
              group=root
              mode=0640
    tags:
      - zones
    notify:
      - Restart shorewall

  - name: Install zones
    template: src=etc/shorewall/zones.j2
              dest=/etc/shorewall/zones
              owner=root
              group=root
              mode=0640
              backup=yes
    tags:
      - zones
    notify:
      - Restart shorewall


### HOSTS
  - name: Create /etc/shorewall/hosts.d
    file: path=/etc/shorewall/hosts.d
          owner=root
          group=root
          state=directory
    tags:
      - hosts

  - name: Install /etc/shorewall/hosts.d/root
    template: src=etc/shorewall/hosts.d/root.j2
              dest=/etc/shorewall/hosts.d/root
              owner=root
              group=root
              mode=0640
    tags:
      - hosts
    notify:
      - Restart shorewall

  # Edit multicast interface here
  - name: Install hosts
    template: src=etc/shorewall/hosts.j2
              dest=/etc/shorewall/hosts
              owner=root
              group=root
              mode=0640
              backup=yes
    tags:
      - hosts
    notify:
      - Restart shorewall


### POLICY
  - name: Create /etc/shorewall/policy.d
    file: path=/etc/shorewall/policy.d
          owner=root
          group=root
          state=directory
    tags:
      - policy

  - name: Install /etc/shorewall/policy.d/root
    template: src=etc/shorewall/policy.d/home.j2
              dest=/etc/shorewall/policy.d/root
              owner=root
              group=root
              mode=0640
    tags:
      - policy
    notify:
      - Restart shorewall

  - name: Install policy
    template: src=etc/shorewall/policy.j2
              dest=/etc/shorewall/policy
              owner=root
              group=root
              mode=0640
              backup=yes
    tags:
      - policy
    notify:
      - Restart shorewall


### RULES
  - name: Create /etc/shorewall/rules.d
    file: path=/etc/shorewall/rules.d
          owner=root
          group=root
          state=directory
    tags:
      - rules

  - name: Install /etc/shorewall/rules.d/root
    template: src=etc/shorewall/rules.d/home.j2
              dest=/etc/shorewall/rules.d/root
              owner=root
              group=root
              mode=0640
    tags:
      - rules
    notify:
      - Restart shorewall

### OTHER CONFIGURATIONS
  - name: Install other configurations
    template: src=etc/shorewall/${item}.j2
              dest=/etc/shorewall/${item}
              owner=root
              group=root
              mode=0640
              backup=yes
    with_items:
      - rules
      - blrules
      - routestopped
    tags:
      - config
      - rules
    notify:
      - Restart shorewall

  - name: Install interfaces
    template: src=etc/shorewall/interfaces_home.j2
              dest=/etc/shorewall/interfaces
              owner=root
              group=root
              mode=0640
              backup=yes
    tags:
      - config
      - interfaces
    notify:
      - Restart shorewall


  - name: Enable shorewall.conf
    template: src=etc/shorewall/shorewall.conf.j2
              dest=/etc/shorewall.conf
              owner=root
              group=root
              mode=0640
              backup=yes
    tags:
      - config
    notify:
      - Restart shorewall

  - name: Enable startup
    lineinfile: dest=/etc/shorewall/shorewall.conf
                regexp='^STARTUP_ENABLED'
                line='STARTUP_ENABLED=Yes'
    tags:
      - config

  - name: Enable startup
    lineinfile: dest=/etc/sysconfig/shorewall
                regexp='^startup'
                line='startup=1'
    when: ansible_os_family == "RedHat"
    tags:
      - config

  - name: Enable Shorwall startup
    lineinfile: dest=/etc/default/shorewall
                regexp='^startup='
                line='startup=1'
    tags:
      - config
    when: ansible_os_family == "Debian"
    notify:
      - Restart shorewall

  - name: Stop iptables
    service: name=iptables
             state=stopped
             enabled=no
    when: ansible_os_family == "RedHat"

  - name: Stop ufw
    service: name=ufw
             state=stopped
             enabled=no
    ignore_errors: yes
    when: ansible_os_family == "Debian"

  - name: Start shorewall
    service: name=shorewall
             state=started
             enabled=yes

### UBUNTU FIX
  - name: Fix Enable shorewall
    command: sysv-rc-conf shorewall on
    when: ansible_distribution == "Ubuntu"
    tags:
      - fix
      - ubuntu

  - name: Fix remove shit from /etc/hosts
    lineinfile: dest=/etc/hosts
                regexp='^127.0.1.1'
                state=absent
    when: ansible_distribution == "Ubuntu"
    tags:
      - fix
      - ubuntu

  handlers:
    - name: Restart shorewall
      service: name=shorewall
               state=restarted
