---
- hosts: all

  tasks:
  - name: Install shorewall
    yum: name=shorewall
         state=installed

  - name: Create /etc/shorewall/params.d
    file: path=/etc/shorewall/params.d
          owner=root
          group=root
          state=directory

  - name: Create /etc/shorewall/rules.d
    file: path=/etc/shorewall/rules.d
          owner=root
          group=root
          state=directory

  - name: Install zones
    template: src=etc/shorewall/zones.j2
              dest=/etc/shorewall/zones
              owner=root
              group=root
              mode=0640

  - name: Install interfaces
    template: src=etc/shorewall/interfaces.j2
              dest=/etc/shorewall/interfaces
              owner=root
              group=root
              mode=0640

  - name: Install policy
    template: src=etc/shorewall/policy.j2
              dest=/etc/shorewall/policy
              owner=root
              group=root
              mode=0640

  - name: Install rules
    template: src=etc/shorewall/rules.j2
              dest=/etc/shorewall/rules
              owner=root
              group=root
              mode=0640

  - name: Enable shorewall
    template: src=etc/shorewall/shorewall.conf.j2
              dest=/etc/shorewall.conf
              owner=root
              group=root
              mode=0640

  - name: Enable multicast
    lineinfile: dest=/etc/shorewall/shorewall.conf
                regexp='^MULTICAST='
                line='MULTICAST=Yes'

  - name: Install /etc/shorewall/params.d/root
    template: src=etc/shorewall/params.d/root.j2
              dest=/etc/shorewall/params.d/root
              owner=root
              group=root
              mode=0640

  - name: Enable root in /etc/shorewall/params
    lineinfile: dest=/etc/shorewall/params
                regexp='^INCLUDE /etc/shorewall/params.d/root'
                insertbefore='^#LAST'
                line='INCLUDE /etc/shorewall/params.d/root'


  - name: Install /etc/shorewall/rules.d/root
    template: src=etc/shorewall/rules.d/root.j2
              dest=/etc/shorewall/rules.d/root
              owner=root
              group=root
              mode=0640

  - name: Enable root in /etc/shorewall/rules
    lineinfile: dest=/etc/shorewall/rules
                regexp='^INCLUDE /etc/shorewall/rules.d/root'
                insertbefore='^#LAST'
                line='INCLUDE /etc/shorewall/rules.d/root'


  - name: Stop iptables
    service: name=iptables
             state=stopped
             enabled=no

#  - name: Restart shorewall
#    shell: /etc/init.d/shorewall restart
#    service: name=shorewall
#             state=restarted
#             enabled=yes
