#
# Shorewall firewall
#
# TODO: dhcp from networks.yml
---
- hosts: all

  vars_files:
    - networks.yml

  tasks:
  - name: Install shorewall
    yum: name=shorewall
         state=installed
    when: ansible_os_family == "RedHat"
    tags:
      - packages

  - name: Install shorewall
    apt: name=shorewall
         state=installed
    when: ansible_os_family == "Debian"
    tags:
      - packages

### PARAMETERS
  - name: Create /etc/shorewall/params.d
    file: path=/etc/shorewall/params.d
          owner=root
          group=root
          state=directory
    tags:
      - parameters

  - name: Install /etc/shorewall/params.d/root
    template: src=etc/shorewall/params.d/root.j2
              dest=/etc/shorewall/params.d/root
              owner=root
              group=root
              mode=0640
    tags:
      - parameters
    notify:
      - Restart shorewall

  - name: Install params
    template: src=etc/shorewall/params.j2
              dest=/etc/shorewall/params
              owner=root
              group=root
              mode=0640
              backup=yes
    tags:
      - parameters
    notify:
      - Restart shorewall

### ZONES
  - name: Create /etc/shorewall/zones.d
    file: path=/etc/shorewall/zones.d
          owner=root
          group=root
          state=directory
    tags:
      - zones

  - name: Install /etc/shorewall/zones.d/root
    template: src=etc/shorewall/zones.d/root.j2
              dest=/etc/shorewall/zones.d/root
              owner=root
              group=root
              mode=0640
    tags:
      - zones
    notify:
      - Restart shorewall

  - name: Install zones
    template: src=etc/shorewall/zones.j2
              dest=/etc/shorewall/zones
              owner=root
              group=root
              mode=0640
              backup=yes
    tags:
      - zones
    notify:
      - Restart shorewall


### HOSTS
  - name: Create /etc/shorewall/hosts.d
    file: path=/etc/shorewall/hosts.d
          owner=root
          group=root
          state=directory
    tags:
      - hosts

  - name: Install /etc/shorewall/hosts.d/root
    template: src=etc/shorewall/hosts.d/root.j2
              dest=/etc/shorewall/hosts.d/root
              owner=root
              group=root
              mode=0640
    tags:
      - hosts
    notify:
      - Restart shorewall

  # Edit multicast interface here
  - name: Install hosts
    template: src=etc/shorewall/hosts.j2
              dest=/etc/shorewall/hosts
              owner=root
              group=root
              mode=0640
              backup=yes
    tags:
      - hosts
    notify:
      - Restart shorewall


### POLICY
  - name: Create /etc/shorewall/policy.d
    file: path=/etc/shorewall/policy.d
          owner=root
          group=root
          state=directory
    tags:
      - policy

  - name: Install /etc/shorewall/policy.d/root
    template: src=etc/shorewall/policy.d/root.j2
              dest=/etc/shorewall/policy.d/root
              owner=root
              group=root
              mode=0640
    tags:
      - policy
    notify:
      - Restart shorewall

  - name: Install policy
    template: src=etc/shorewall/policy.j2
              dest=/etc/shorewall/policy
              owner=root
              group=root
              mode=0640
              backup=yes
    tags:
      - policy
    notify:
      - Restart shorewall


### RULES
  - name: Create /etc/shorewall/rules.d
    file: path=/etc/shorewall/rules.d
          owner=root
          group=root
          state=directory
    tags:
      - rules

  - name: Install /etc/shorewall/rules.d/root
    template: src=etc/shorewall/rules.d/root.j2
              dest=/etc/shorewall/rules.d/root
              owner=root
              group=root
              mode=0640
    tags:
      - rules
    notify:
      - Restart shorewall


  - name: Install /etc/shorewall/rules.d/sysop
    template: src=etc/shorewall/rules.d/sysop.j2
              dest=/etc/shorewall/rules.d/sysop
              owner=root
              group=root
              mode=0640
    tags:
      - rules
    notify:
      - Restart shorewall


  - name: Install /etc/shorewall/rules
    template: src=etc/shorewall/rules.j2
              dest=/etc/shorewall/rules
              owner=root
              group=root
              mode=0640
              backup=yes
    tags:
      - rules
    notify:
      - Restart shorewall

#  - name: Enable root in /etc/shorewall/rules
#    lineinfile: dest=/etc/shorewall/rules
#                regexp='^INCLUDE /etc/shorewall/rules.d/root'
#                insertbefore='^#LAST'
#                line='INCLUDE /etc/shorewall/rules.d/root'


### OTHER
  - name: Install interfaces
    template: src=etc/shorewall/interfaces.j2
              dest=/etc/shorewall/interfaces
              owner=root
              group=root
              mode=0640
              backup=yes
    tags:
      - misc
    notify:
      - Restart shorewall

  - name: Install routestopped
    template: src=etc/shorewall/routestopped.j2
              dest=/etc/shorewall/routestopped
              owner=root
              group=root
              mode=0640
              backup=yes
    tags:
      - misc
    notify:
      - Restart shorewall

  - name: Enable shorewall
    template: src=etc/shorewall/shorewall.conf.j2
              dest=/etc/shorewall.conf
              owner=root
              group=root
              mode=0640
              backup=yes
    tags:
      - misc
    notify:
      - Restart shorewall

#  - name: Enable multicast
#    lineinfile: dest=/etc/shorewall/shorewall.conf
#                regexp='^MULTICAST='
#                line='MULTICAST=Yes'


  - name: Enable Shorwall startup
    lineinfile: dest=/etc/default/shorewall
                regexp='^startup='
                line='startup=1'
    tags:
      - config
    when: ansible_os_family == "Debian"
    notify:
      - Restart shorewall

  - name: Stop iptables
    service: name=iptables
             state=stopped
             enabled=no
    when: ansible_os_family == "RedHat"

  - name: Stop ufw
    service: name=ufw
             state=stopped
             enabled=no
    ignore_errors: yes
    when: ansible_os_family == "Debian"

  - name: Start shorewall
    service: name=shorewall
             state=started
             enabled=yes

  handlers:
    - name: Restart shorewall
      service: name=shorewall
               state=restarted
