#
# Slurm Scheduler
#
---
- hosts: all
  vars_files:
    - slurm_vars.yml
    - mariadb_vars.yml

  vars:
    is_master: "'$inventory_hostname' == '$master'"
    is_slurm_master: "'$inventory_hostname' == '$slurm_master'"
    is_slurm_backup: "'$inventory_hostname' == '$slurm_backup'"

  tasks:
  - name: Install slurm packages
    yum: name=$item
         state=installed
         enablerepo=$slurm_repo
    with_items:
      - munge
      - slurm
      - slurm-munge
      - slurm-pam_slurm
      - slurm-perlapi
      - slurm-plugins
      - slurm-sjobexit
      - slurm-sjstat
      - slurm-slurmdbd
      - slurm-sql
      - slurm-torque
    tags:
      - packages

  # https://code.google.com/p/munge/wiki/InstallationGuide
  - name: Set munge user
    lineinfile: dest=/etc/sysconfig/munge
                regexp='^USER'
                line='USER="munge"'

  - name: Fix /var/log/munge/munged.log
    file: path=/var/log/munge/munged.log
          owner=munge
          group=munge
    ignore_errors: yes

  - name: Setup munge key
    copy: src=etc/munge/munge.key
          dest=/etc/munge/munge.key
          owner=munge
          group=munge
          mode=0600

    notify:
      - Restart munge

  - name: Start munge
    service: name=munge
             state=started
             enabled=yes

  - name: Setup slurmdbd mysql db
    mysql_db: db=$slurm_db
              login_user=root
              login_password=$password
              login_unix_socket=$socket
    only_if: '$is_master'

  - name: Setup slurmdbd mysql user
    mysql_user: name=$slurm_user password=$slurm_password priv=${slurm_db}.*:ALL
                login_user=root
                login_password=$password
                login_unix_socket=$socket
    only_if: '$is_master'

  - name: Create slurm group
    group: name=slurm
           state=present
  - name: Create slurm user
    user: name=slurm
          comment="Slurm Scheduler"
          state=present
          password=*
          group=slurm

  - name: Create slurm directories
    file: path=/var/$item/slurm
          owner=slurm
          group=slurm
          state=directory
    with_items:
      - log
      - run
      - lib
    tags:
      - directories

  - name: Install /etc/slurm/slurmdbd.conf
    template: src=etc/slurm/slurmdbd.conf.j2
              dest=/etc/slurm/slurmdbd.conf
              owner=slurm
              group=slurm
              mode=0600
    notify:
      - Restart slurmdbd
    only_if: '$is_slurm_master or $is_slurm_backup'

  - name: Start slurmdbd
    service: name=slurmdbd
             state=started
             enabled=yes
    only_if: '$is_slurm_master or $is_slurm_backup'

  - name: Create state directory
    file: path=$slurm_state
          owner=slurm
          group=slurm
          state=directory
    tags:
      - state
    only_if: '$is_slurm_master'

  - name: Create spool directory
    file: path=${slurm_state}/slurmd
          owner=slurm
          group=slurm
          state=directory
    tags:
      - state
    only_if: '$is_slurm_master'

  - name: Install /etc/slurm/slurm.conf
    template: src=etc/slurm/slurm.conf.j2
              dest=/etc/slurm/slurm.conf
              owner=slurm
              group=slurm
              mode=0600
    notify:
      - Restart slurm

  - name: Start slurm
    service: name=slurm
             state=started
             enabled=yes

  handlers:
    - name: Restart munge
      service: name=munge
               state=restarted

    - name: Restart slurmdbd
      service: name=slurmdbd
               state=restarted

    - name: Restart slurm
      service: name=slurm
               state=restarted
