#
# Slurm Scheduler
#
---
- hosts: all
  vars_files:
    - slurm_vars.yml
    - mariadb_vars.yml

  vars:
    is_master: "'$inventory_hostname' == '$master'"
    is_slurm_master: "'$inventory_hostname' == '$slurm_master'"
    is_slurm_backup: "'$inventory_hostname' == '$slurm_backup'"

  tasks:
  - name: Install slurm packages
    yum: name=$item
         state=installed
         enablerepo=$slurm_repo
    with_items:
      - munge
      - slurm
      - slurm-munge
      - slurm-pam_slurm
      - slurm-perlapi
      - slurm-plugins
      - slurm-sjobexit
      - slurm-sjstat
      - slurm-slurmdbd
      - slurm-sql
      - slurm-torque
      - mailx
    tags:
      - packages

  # https://code.google.com/p/munge/wiki/InstallationGuide
  - name: Set munge user
    lineinfile: dest=/etc/sysconfig/munge
                regexp='^USER'
                line='USER="munge"'
    tags:
      - munge

  - name: Set munge permissions
    file: path=/var/${item}/munge
          owner=munge
          group=munge
          state=directory
    with_items:
      - run
      - lib
      - log
    tags:
      - munge

  - name: Set munge permissions /etc/munge
    file: path=/etc/munge
          owner=munge
          group=munge
          state=directory
    tags:
      - munge

  - name: Setup munge key
    copy: src=etc/munge/munge.key
          dest=/etc/munge/munge.key
          owner=munge
          group=munge
          mode=0600
    tags:
      - munge
    notify:
      - Restart munge

  - name: Start munge
    service: name=munge
             state=started
             enabled=yes

  - name: Setup slurmdbd mysql db
    mysql_db: db=$slurm_db
              login_user=root
              login_password=$password
              login_unix_socket=$socket
    only_if: '$is_master'
    tags:
      - slurm

  - name: Setup slurmdbd mysql user
    mysql_user: name=$slurm_user password=$slurm_password priv=${slurm_db}.*:ALL
                login_user=root
                login_password=$password
                login_unix_socket=$socket
    only_if: '$is_master'
    tags:
      - slurm

  - name: Create slurm group
    group: name=slurm
           state=present
    tags:
      - slurm

  - name: Create slurm user
    user: name=slurm
          comment="Slurm Scheduler"
          state=present
          password=*
          group=slurm
    tags:
      - slurm

  - name: Create slurm directories
    file: path=/var/$item/slurm
          owner=slurm
          group=slurm
          state=directory
    with_items:
      - log
      - run
      - lib
    tags:
      - slurm


### DATABASE
  - name: Install /etc/slurm/slurmdbd.conf
    template: src=etc/slurm/slurmdbd.conf.j2
              dest=/etc/slurm/slurmdbd.conf
              owner=slurm
              group=slurm
              mode=0600
    notify:
      - Restart slurmdbd
    only_if: '$is_slurm_master or $is_slurm_backup'
    tags:
      - slurm
      - database

  - name: Start slurmdbd
    service: name=slurmdbd
             state=started
             enabled=yes
    only_if: '$is_slurm_master or $is_slurm_backup'
    tags:
      - slurm
      - database


  - name: Create cluster
    shell: /usr/bin/sacctmgr -i create cluster name=$slurm_cluster
    only_if: '$is_slurm_master'
    ignore_errors: yes
    tags:
      - slurm

  - name: Create test account
    shell: /usr/bin/sacctmgr -i add account test
    only_if: '$is_slurm_master'
    ignore_errors: yes
    tags:
      - slurm

  - name: Enable test account
    shell: /usr/bin/sacctmgr -i add user admin defaultaccount=test
    only_if: '$is_slurm_master'
    ignore_errors: yes
    tags:
      - slurm


  - name: Create state directory
    file: path=$slurm_state
          owner=slurm
          group=slurm
          state=directory
    tags:
      - state
    only_if: '$is_slurm_master'
    tags:
      - slurm

  - name: Create checkpoint directory
    file: path=$slurm_checkpoint
          owner=slurm
          group=slurm
          state=directory
    tags:
      - state
    only_if: '$is_slurm_master'
    tags:
      - slurm

  - name: Create spool directory
    file: path=/var/spool/slurmd
          owner=slurm
          group=slurm
          state=directory
    tags:
      - slurm

  - name: Install /etc/slurm/slurm.conf
    template: src=etc/slurm/slurm.conf.j2
              dest=/etc/slurm/slurm.conf
              owner=slurm
              group=slurm
              mode=0644
    notify:
      - Restart slurm
    tags:
      - slurm

  - name: Install /etc/sysconfig/slurm
    template: src=etc/sysconfig/slurm.j2
              dest=/etc/sysconfig/slurm
              owner=slurm
              group=slurm
              mode=0644
    notify:
      - Restart slurm
    tags:
      - slurm

# TODO:
#  - name: Enable GLB
#    template: src=etc/sysconfig/slurm.glb.j2
#              dest=/etc/sysconfig/slurm.glb
#              owner=slurm
#              group=slurm
#              mode=0644
#    notify:
#      - Restart slurmdbd
#    tags:
#      - slurm

  - name: Install logrotate
    template: src=etc/logrotate.d/slurm.j2
              dest=/etc/logrotate.d/slurm
              owner=slurm
              group=slurm
              mode=0644
    tags:
      - slurm

  - name: Enable slurmctld service
    lineinfile: dest=/etc/services
                regexp="^slurmctld 6817/$item"
                line="slurmctld 6817/$item"
    with_items:
     - tcp
     - udp
    tags:
      - config
      - services

  - name: Enable slurmd service
    lineinfile: dest=/etc/services
                regexp="^slurmd 6818/$item"
                line="slurmd 6818/$item"
    with_items:
     - tcp
     - udp
    tags:
      - config
      - services

  - name: Enable slurmdbd service
    lineinfile: dest=/etc/services
                regexp="^slurmdbd 6819/$item"
                line="slurmdbd 6819/$item"
    with_items:
     - tcp
     - udp
    tags:
      - config
      - services

  - name: Start slurm
    service: name=slurm
             state=started
             enabled=yes

  handlers:
    - name: Restart munge
      service: name=munge
               state=restarted

    - name: Restart slurmdbd
      service: name=slurmdbd
               state=restarted

    - name: Restart slurm
      service: name=slurm
               state=restarted
