# This play secures SSH
# run it with sudo
#
# Generate passwordless root key for intra root node logins:
#
#     ssh-keygen -C "root key" -f keys/nopass
#
---
- hosts: all

  vars_files:
    - networks.yml
    - [ "vars/{{ansible_os_family}}.yml", "vars/Defaults.yml" ]

  tasks:
    - name: Secure SSH
      template: src=etc/ssh/sshd_config.j2
                dest=/etc/ssh/sshd_config
                owner=root
                group=root
                mode=0600
                backup=yes
      notify:
        - Restart sshd
      tags:
        - config

    - name: Fix sftp subsystem in sshd_config
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp='^Subsystem sftp'
                  line='Subsystem sftp /usr/lib/openssh/sftp-server'
      when: ansible_os_family == "Debian"
      notify:
        - Restart sshd
      tags:
        - config

    - name: Create root SSH directory
      file: path=/root/.ssh
            owner=root
            group=root
            mode=700
            state=directory
      tags:
        - key

    - name: Install root private key
      copy: src=keys/nopass
            dest=/root/.ssh/id_rsa
            owner=root
            group=root
            mode=600
      tags:
        - key

    - name: Install root public key
      authorized_key: user=root
                      key='$FILE(keys/nopass.pub)'
      tags:
        - key

  handlers:
    - name: Restart sshd
      service: name={{service_sshd}}
               state=restarted
