# This play secures SSH
# run it with sudo
---
- hosts: all

  tasks:
    - name: Secure SSH Server
      template: src=etc/ssh/sshd_config.j2
                dest=/etc/ssh/sshd_config
                owner=root
                group=root
                mode=0600
                backup=yes
      notify:
        - reload sshd
      tags:
        - config

  handlers:
    - name: reload sshd
      service: name=sshd
               state=reloaded
