---
- hosts: all

  tasks:

  - name: Enable loghost
    template: src=etc/syslog-ng/conf.d/loghost
              dest=/etc/syslog-ng/conf.d/10-loghost
              owner=root
              group=root
              mode=0644

  - name: Enable directory creation
    lineinfile: dest=/etc/syslog-ng/syslog-ng.conf
                regexp='create_dirs \('
                line='create_dirs (yes);'

  - name: Restart syslog-ng
    service: name=syslog-ng
             state=restarted
             enabled=yes
