#
# syslog-ng remote log client
#
---
- hosts: all

# lineinfile bug?

  tasks:
  - name: Enable loghost client
    template: src=etc/syslog-ng/conf.d/client.{{ ansible_distribution }}
              dest=/etc/syslog-ng/conf.d/20-client
              owner=root
              group=root
              mode=0644
    notify:
      - Restart syslog-ng
    tags:
      - config

  handlers:
    - name: Restart syslog-ng
      service: name=syslog-ng
               state=restarted
