---
- hosts: all

  tasks:
#  - name: Install syslog-ng packages
#    yum: name=$item
#         state=installed
#    with_items:
#      - syslog-ng
#      - syslog-ng-libdbi
#    tags:
#      - packages

  - name: Stop rsyslog
    service: name=rsyslog
             state=stopped
             enabled=no
    tags:
      - prepare
    ignore_errors: yes

  - name: Uninstall rsyslog for sure
    yum: name=rsyslog
         state=absent
    when: ansible_os_family == "RedHat"
    tags:
      - prepare

  - name: Uninstall rsyslog for sure
    apt: name=rsyslog
         state=absent
    when: ansible_os_family == "Debian"
    tags:
      - prepare


### REDHAT
  - name: Install umask repo
    template: src=etc/yum.repos.d/umask.repo.j2
              dest=/etc/yum.repos.d/umask.repo
              owner=root
              group=root
    when: ansible_os_family == "RedHat"
    tags:
      - repo
      - packages

  - name: Install syslog-ng packages
    yum: name=syslog-ng
         state=latest
         enablerepo=umask
    when: ansible_os_family == "RedHat"
    tags:
      - packages

  - name: Install syslog-ng-libdbi packages
    yum: name=syslog-ng-libdbi
         state=latest
         enablerepo=umask
    when: ansible_os_family == "RedHat"
    tags:
      - packages

### DEBIAN
  - name: Install packages
    apt: name=$item
         state=installed
    with_items:
      - syslog-ng
      - syslog-ng-mod-json
      - syslog-ng-mod-mongodb
    when: ansible_os_family == "Debian"
    tags:
      - packages

### CONFIGURATION
  - name: Create /etc/syslog-ng/conf.d
    file: path=/etc/syslog-ng/conf.d
          owner=root
          group=root
          state=directory
    tags:
      - config
      - directories

  - name: Install /etc/syslog-ng/syslog-ng.conf
    template: src=etc/syslog-ng/syslog-ng.conf.j2
              dest=/etc/syslog-ng/syslog-ng.conf
              owner=root
              group=root
              backup=yes
    when: ansible_os_family == "RedHat"
    tags:
      - config

  - name: Install /etc/syslog-ng/syslog-ng.conf
    template: src=etc/syslog-ng/syslog-ng.{{ansible_distribution}}.conf.j2
              dest=/etc/syslog-ng/syslog-ng.conf
              owner=root
              group=root
              backup=yes
    when: ansible_distribution == "Ubuntu"
    tags:
      - config

### SERVICE
  - name: Start syslog-ng
    service: name=syslog-ng
             state=started
             enabled=yes

  handlers:
    - name: Restart syslog-ng
      service: name=syslog-ng
               state=restarted
