---
- hosts: all

  tasks:
  - name: Install prerequisite packages
    yum: name=$item
         state=installed
    with_items:
      - syslog-ng
      - syslog-ng-libdbi
    tags:
      - packages

  - name: Uninstall rsyslog for sure
    yum: name=rsyslog
         state=absent

  - name: Enable ISO 8601 timestamps
    lineinfile: dest=/etc/syslog-ng/syslog-ng.conf
                regexp='ts_format\(iso\);'
                insertafter='^options {'
                line='ts_format(iso);'
    notify:
      - Restart syslog-ng

  - name: Create /etc/syslog-ng/conf.d
    file: path=/etc/syslog-ng/conf.d
          owner=root
          group=root
          state=directory

  - name: Enable /etc/syslog-ng/conf.d
    lineinfile: dest=/etc/syslog-ng/syslog-ng.conf
                regexp='include "conf.d";'
                insertafter='^filter f_cron'
                line='include "conf.d";'
    notify:
      - Restart syslog-ng

  - name: Start syslog-ng
    service: name=syslog-ng
             state=started
             enabled=yes

  handlers:
    - name: Restart syslog-ng
      service: name=syslog-ng
               state=restarted
