---
- hosts: all

  tasks:
  - name: Install Webmin Repo
    template: src=etc/yum.repos.d/webmin.repo.j2
              dest=/etc/yum.repos.d/webmin.repo
              owner=root
              group=root
              mode=0644

  - name: Install Webmin key
    command: rpm --import http://www.webmin.com/jcameron-key.asc

  - name: Install Webmin
    yum: name=webmin
         state=installed

  - name: Install /etc/shorewall/rules.d/webmin
    template: src=etc/shorewall/rules.d/webmin.j2
              dest=/etc/shorewall/rules.d/webmin
              owner=root
              group=root
              mode=0640

#  - name: Enable webmin in /etc/shorewall/rules
#    lineinfile: dest=/etc/shorewall/rules
#                regexp='^INCLUDE /etc/shorewall/rules.d/webmin'
#                insertbefore='^#LAST'
#                line='INCLUDE /etc/shorewall/rules.d/webmin'

  - name: restart shorewall
    service: name=shorewall
             state=restarted