#!/bin/bash
gbn=$(basename $0)
gdn=$(cd $(dirname $0); pwd)
jockey_root=${gdn}

default=centos63

### defaults for OS X
host=${jockey_root}/.host
if [ -r ${host} ] ; then
  source ${host}
fi

usrlocal=/usr
if [ ! -z "${OSTYPE/darwin/}" ]; then
  usrlocal=/usr/local
fi

### args
cmd=${1:-test}
shift
arg=$1

### dnsmasq
jockey_ip=${ip:-10.1.1.254}

masq_conf=${jockey_root}/.masq
masq_root=${jockey_root}/boot

ipxe_root=${masq_root}/pxelinux.cfg

### http server (nginx)
http_conf=${jockey_root}/.http
http_listen=${jockey_ip}:8080
http_root=${masq_root}

nginx_bin=${usrlocal}/sbin/nginx
dnsmasq_bin=${usrlocal}/sbin/dnsmasq

### functions
function jockey/exit() {
  local _c
  for _c in ${http_conf} ${masq_conf} ; do
    if [ -r ${_c} ] ; then
      rm -f ${_c}
    fi
  done
}
trap jockey/exit INT TERM EXIT

function help/jockey() {
  cat <<EOF

Primordial boot manager

Usage: jockey cmd  args    description
              host IP      - set host IP
              kick MAC     - create a kickstart for a MAC address on host IP
              pass         - generate a password
              dump         - listen to bootp requests
              http         - start ngnix http server on host IP
              masq         - start dnsmasq server on host IP
EOF
  exit 1
}

function jockey/__pass() {
  awk '{print(substr($0,1,4))"-"(substr($0,5,4))"-"(substr($0,9,4))"-"(substr($0,13,4))}'
}

function jockey/_pass() {
  awk '{print((substr($0,1,4))(substr($0,5,4)))}'
}

function jockey/pass() {
  local _r=""
  for i in {1..5}; do _r=${_r}$RANDOM; done

  echo ${_r} | jockey/_pass
}

function jockey/netpass() {
  curl -s "https://www.random.org/strings/?num=1&len=16&digits=on&unique=off&&rnd=new&format=plain" | \
  jockey/_pass
}

function jockey/mac() {
  local _mac=$*
  if [ "${1:0:1}" = "@" ] ; then
    local _host="${1:1}"
    _mac=$(VBoxManage showvminfo "${_host}" | \
    grep 'NIC 1:' | \
    sed 's/.*MAC:\ *//' | \
    sed 's/,.*//' | \
    sed 's/\(.\{2\}\)/&-/g;s/-$//')
  fi
  echo "${_mac}"
}

### main
case ${cmd} in
  pass|netpass)
    jockey/${cmd}
  ;;

  host)
    if [ "${cmd:0:1}" = "@" ] ; then
      dev="${arg}"
      ip=$(ifconfig vboxnet5 inet | grep inet | cut -d" " -f 2)
    else
      ip="${arg}"
    fi

    echo "ip=${ip}" | tee ${host}
  ;;

  centos63|centos64|squeeze|wheezy|quantal|raring|kali|harmonia)
    if [ -z "${arg}" ] ; then help/jockey; fi

    ### args
    default=${cmd}
    mac=$(jockey/mac ${arg})
    shift
    addr=${1:-10.1.1.1}
    shift
    name=${1:-root-01}

    http_listen=${jockey_ip}:8080

    pass=$(jockey/pass)
    echo ""
    echo "Space Jockey Kickstart Generator for Linux"
    echo ""
    echo "root password for ${mac}: ${pass}"
    echo ""
    root_pass=$(openssl passwd -1 "${pass}")
    ks=$(echo "${mac}" | sed s/:/-/g | tr '[:upper:]' '[:lower:]')
    echo "${pass}" > ${jockey_root}/${ks}.pass

    ### kickstart
    cat ${jockey_root}/kickstart.${default} | \
    awk -v p=${root_pass} \
        -v q=${pass} \
        -v l=${http_listen} \
        -v i=${interface} \
        -v a=${addr} \
        -v n=${name} \
    '{gsub("ROOT_PASSWORD_PLAIN",q);
      gsub("ROOT_PASSWORD",p);
      gsub("HTTP_LISTEN",l);
      gsub("SYSTEM_NAME",n);
      gsub("SYSTEM_ADDR",a);
      gsub("INTERFACE",i); print}' \
    > ${http_root}/${ks}.ks

    ### pxelinux
    kickstart=${http_listen}/${ks}.ks
    cat ${jockey_root}/boot/default | \
    awk -v k=${kickstart} -v d=${default} -v i=${interface} \
    '{gsub("KICKSTART",k); gsub("_DEFAULT",d); gsub("INTERFACE",i); print}' \
    > ${ipxe_root}/01-${ks}
  ;;

  local|memtest|detect|firmware|cirros|tiny|kali)
    if [ -z "${arg}" ] ; then help/jockey; fi

    mac=$(jockey/mac ${arg})

    http_listen=${jockey_ip}:8080
    ks=$(echo "${mac}" | sed s/:/-/g | tr '[:upper:]' '[:lower:]')
    kickstart=${http_listen}/${ks}.ks
    default=${cmd}
    cat ${jockey_root}/boot/default | \
    awk -v k=${kickstart} -v d=${default} '{gsub("KICKSTART",k); gsub("_DEFAULT",d); print}' \
    > ${ipxe_root}/01-${ks}
  ;;

  esxi)
    if [ -z "${arg}" ] ; then help/jockey; fi

    mac=$(jockey/mac ${arg})

    http_listen=${jockey_ip}:8080
    default=${cmd}

    pass=$(jockey/pass)
    echo ""
    echo "Space Jockey Kickstart Generator for ESXi"
    echo ""
    echo "root password for ${mac}: ${pass}"
    echo ""
    root_pass=$(openssl passwd -1 "${pass}")
    ks=$(echo "${mac}" | sed s/:/-/g | tr '[:upper:]' '[:lower:]')
    echo "${pass}" > ${jockey_root}/${ks}.pass

    ### kickstart
    cat ${jockey_root}/kickstart.esxi | \
    awk -v p=${pass} '{gsub("ROOT_PASSWORD",p); print}' \
    > ${http_root}/${ks}.ks

    kickstart=${http_listen}/${ks}.ks
    cat ${jockey_root}/boot/default | \
    awk -v d=${default} '{gsub("_DEFAULT",d); print}' \
    > ${ipxe_root}/01-${ks}

    cat ${jockey_root}/boot/esxi/repo/BOOT.CFG | \
    sed "s/\//repo\//g" | \
    awk -v l="http://${kickstart}" '{gsub("^kernelopt.*","kernelopt=ks=" l);print}' \
    > ${jockey_root}/boot/esxi/boot.cfg

  ;;

  dump)
    tcpdump -i ${arg} port bootps
  ;;

  http)
    cat ${jockey_root}/http | \
    awk -v p=${http_root} -v l=${http_listen} '{gsub("HTTP_ROOT",p); gsub("HTTP_LISTEN",l); print}' \
    > ${http_conf}
    echo "Starting HTTP Server..."
    echo "Press Ctrl+C to exit"
    ${nginx_bin} -c ${http_conf}
  ;;

  boot)
    cat ${jockey_root}/masq | \
    awk -v p=${masq_root} -v l=${jockey_ip} '{gsub("DNSMASQ_LISTEN",l); gsub("DNSMASQ_ROOT",p); print}' \
    > ${masq_conf}

    echo "Starting DNSmasq server..."
    echo "Press Ctrl+C to exit"
    sudo ${dnsmasq_bin} -d -C ${masq_conf}
  ;;

  ipmi)
    sub=${arg}
    shift
    arg=$1
    ipmi=${jockey_root}/.ipmi
    if [ -r ${ipmi} ] ; then
      source ${ipmi}
    fi

    case $sub in
      user)
        shift
        echo "user=${arg};pass=${1:-admin}" > ${ipmi}
      ;;
      tool)
        ip=${arg}
        shift
        ipmitool -I lanplus -U ${user} -P ${pass} -H ${ip} $*
      ;;
    esac
  ;;
  *)
    help/jockey
  ;;
esac
